-- ============================================================================
-- COLORSHINE MES V2
-- 16_planning_thickness_matrix_plant2000_seed_v2.sql
-- FIX: REVIEW rows may contain incomplete source keys (e.g. source row 98).
--      They are stored for data cleansing but cannot become VALID/ACTIVE until fixed.
-- ============================================================================

-- Recover pgAdmin session if the previous seed failed inside BEGIN.
ROLLBACK;

SET search_path TO mes, public;
BEGIN;

-- REVIEW/staging rows must be preservable even when source Material/ProductGroup is missing.
ALTER TABLE mes.planning_thickness_matrix
    ALTER COLUMN material_code DROP NOT NULL,
    ALTER COLUMN product_group DROP NOT NULL;

-- VALID rows, however, must have usable master keys.
ALTER TABLE mes.planning_thickness_matrix
    DROP CONSTRAINT IF EXISTS ck_pln_thk_valid_required_fields;

ALTER TABLE mes.planning_thickness_matrix
    ADD CONSTRAINT ck_pln_thk_valid_required_fields
    CHECK (
        validation_status <> 'VALID'
        OR (
            NULLIF(BTRIM(material_code), '') IS NOT NULL
            AND BTRIM(material_code) <> '0'
            AND NULLIF(BTRIM(product_group), '') IS NOT NULL
            AND BTRIM(product_group) <> '0'
        )
    );

-- Remove prior Plant 2000 matrix rows from this source before clean reload.
-- Safe here because this is still master-data setup and no released planning run should reference it yet.
DELETE FROM mes.planning_thickness_matrix
WHERE plant_code = '2000'
  AND source_uuid IS NOT NULL;

INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10001',2,'GLAZ70CFPR','GL',70.0,0.25,0.245,0.255,0.23,0.225,0.235,2.0,1.6,2.0,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10002',3,'GLAZ70CFPR','GL',70.0,0.27,0.265,0.275,0.25,0.245,0.255,2.0,1.6,2.0,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10003',4,'GLAZ70CFPR','GL',70.0,0.29,0.285,0.295,0.27,0.265,0.275,2.0,1.6,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10004',5,'GLAZ70CFPR','GL',70.0,0.3,0.295,0.305,0.28,0.275,0.285,2.0,1.6,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10005',6,'GLAZ70CFPR','GL',70.0,0.32,0.315,0.325,0.3,0.295,0.305,2.0,1.6,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10006',7,'GLAZ70CFPR','GL',70.0,0.35,0.345,0.355,0.33,0.325,0.335,2.0,1.6,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10007',8,'GLAZ70CFPR','GL',70.0,0.37,0.365,0.375,0.35,0.345,0.355,2.0,1.6,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10008',9,'GLAZ70CFPR','GL',70.0,0.4,0.395,0.405,0.38,0.375,0.385,2.2,1.6,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10009',10,'GLAZ70CFPR','GL',70.0,0.42,0.415,0.425,0.395,0.39,0.4,2.2,1.6,2.5,'REVIEW','Duplicate business key',false);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10010',11,'GLAZ70CFPR','GL',70.0,0.44,0.435,0.445,0.42,0.415,0.425,2.2,1.6,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10011',12,'GLAZ70CFPR','GL',70.0,0.47,0.465,0.475,0.45,0.445,0.455,2.5,1.6,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10012',13,'GLAZ70CFPR','GL',70.0,0.57,0.565,0.575,0.55,0.545,0.555,2.5,1.6,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10013',14,'GLAZ70CFPR','GL',70.0,0.67,0.665,0.675,0.65,0.645,0.655,2.5,2.2,3.0,'REVIEW','Duplicate business key',false);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10014',15,'GLAZ70CFPR','GL',70.0,0.77,0.765,0.775,0.75,0.745,0.755,2.8,2.5,3.2,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10015',16,'GLAZ70CFPR','GL',70.0,0.87,0.865,0.875,0.85,0.845,0.855,2.8,2.8,3.2,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10016',17,'GLAZ70CFPR','GL',70.0,0.97,0.965,0.975,0.95,0.945,0.955,3.0,2.8,3.2,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10017',18,'GLAZ70CF','GL',70.0,0.25,0.245,0.255,0.23,0.225,0.235,2.0,1.6,2.0,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10018',19,'GLAZ70CF','GL',70.0,0.27,0.265,0.275,0.24,0.235,0.245,2.0,1.6,2.0,'REVIEW','Duplicate business key',false);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10019',20,'GLAZ70CF','GL',70.0,0.29,0.285,0.295,0.27,0.265,0.275,2.0,1.6,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10020',21,'GLAZ70CF','GL',70.0,0.3,0.295,0.305,0.28,0.275,0.285,2.0,1.6,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10021',22,'GLAZ70CF','GL',70.0,0.31,0.305,0.315,0.29,0.285,0.295,2.0,1.6,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10022',23,'GLAZ70CF','GL',70.0,0.35,0.345,0.355,0.33,0.325,0.335,2.0,1.6,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10023',24,'GLAZ70CF','GL',70.0,0.37,0.365,0.375,0.35,0.345,0.355,2.0,1.6,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10024',25,'GLAZ70CF','GL',70.0,0.4,0.395,0.405,0.38,0.375,0.385,2.2,1.6,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10025',26,'GLAZ70CF','GL',70.0,0.42,0.415,0.425,0.395,0.39,0.4,2.2,1.6,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10026',27,'GLAZ70CF','GL',70.0,0.44,0.435,0.445,0.42,0.415,0.425,2.2,1.6,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10027',28,'GLAZ70CF','GL',70.0,0.47,0.465,0.475,0.45,0.445,0.455,2.5,1.6,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10028',29,'GLAZ70CF','GL',70.0,0.57,0.565,0.575,0.55,0.545,0.555,2.5,1.6,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10029',30,'GLAZ70CF','GL',70.0,0.67,0.665,0.675,0.65,0.645,0.655,2.5,2.2,3.0,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10030',31,'GLAZ70CF','GL',70.0,0.77,0.765,0.775,0.75,0.745,0.755,2.8,2.5,3.2,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10031',32,'GLAZ70CF','GL',70.0,0.87,0.865,0.875,0.85,0.845,0.855,2.8,2.8,3.2,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10032',33,'GLAZ70CF','GL',70.0,0.97,0.965,0.975,0.95,0.945,0.955,3.0,2.8,3.2,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10033',34,'GLAZ150CF','GL',150.0,0.25,0.245,0.255,0.21,0.205,0.215,2.0,1.6,2.0,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10034',35,'GLAZ150CF','GL',150.0,0.27,0.265,0.275,0.23,0.225,0.235,2.0,1.6,2.0,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10035',36,'GLAZ150CF','GL',150.0,0.29,0.285,0.295,0.25,0.245,0.255,2.0,1.6,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10036',37,'GLAZ150CF','GL',150.0,0.3,0.295,0.305,0.26,0.255,0.265,2.0,1.6,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10037',38,'GLAZ150CF','GL',150.0,0.32,0.315,0.325,0.28,0.275,0.285,2.0,1.6,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10038',39,'GLAZ150CF','GL',150.0,0.35,0.345,0.355,0.31,0.305,0.315,2.0,1.6,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10039',40,'GLAZ150CF','GL',150.0,0.37,0.365,0.375,0.33,0.325,0.335,2.0,1.6,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10040',41,'GLAZ150CF','GL',150.0,0.4,0.395,0.405,0.36,0.355,0.365,2.2,1.6,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10041',42,'GLAZ150CF','GL',150.0,0.42,0.415,0.425,0.38,0.375,0.385,2.2,1.6,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10042',43,'GLAZ150CF','GL',150.0,0.41,0.405,0.415,0.37,0.365,0.475,2.2,1.6,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10043',44,'GLAZ150CF','GL',150.0,0.47,0.465,0.475,0.43,0.425,0.435,2.5,1.6,2.5,'REVIEW','Duplicate business key',false);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10044',45,'GLAZ150CF','GL',150.0,0.57,0.565,0.575,0.53,0.525,0.535,2.5,1.6,2.5,'REVIEW','Duplicate business key',false);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10045',46,'GLAZ150CF','GL',150.0,0.67,0.665,0.675,0.63,0.625,0.635,2.5,2.2,3.0,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10046',47,'GLAZ150CF','GL',150.0,0.77,0.765,0.775,0.73,0.725,0.735,2.8,2.5,3.2,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10047',48,'GLAZ150CF','GL',150.0,0.87,0.865,0.875,0.83,0.825,0.835,2.8,2.8,3.2,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10048',49,'GLAZ150CF','GL',150.0,0.97,0.965,0.975,0.93,0.925,0.935,3.0,2.8,3.2,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10049',50,'BGLAZ70CF','BGL',70.0,0.5,0.495,0.505,0.43,0.425,0.435,2.5,1.6,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10050',51,'BGLAZ70CF','BGL',70.0,0.47,0.465,0.475,0.4,0.395,0.405,2.5,1.6,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10051',52,'BGLAZ70CF','BGL',70.0,0.45,0.445,0.455,0.38,0.375,0.385,2.5,1.6,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10052',53,'BGLAZ70CF','BGL',70.0,0.43,0.425,0.435,0.36,0.355,0.365,2.2,1.6,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10053',54,'BGLAZ70CF','BGL',70.0,0.4,0.395,0.405,0.33,0.325,0.335,2.2,1.6,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10054',55,'BGLAZ70CF','BGL',70.0,0.38,0.375,0.385,0.32,0.315,0.325,2.0,1.6,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10055',56,'BGLAZ70CF','BGL',70.0,0.35,0.345,0.355,0.29,0.285,0.295,2.0,1.6,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10056',57,'BGLSAZ150CF','BGL',150.0,0.85,0.845,0.855,0.805,0.8,0.81,2.8,2.5,3.0,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10057',58,'BGLSAZ150CF','BGL',150.0,0.9,0.895,0.905,0.855,0.85,0.86,2.8,2.5,3.0,'REVIEW','Duplicate business key',false);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10058',59,'BGLSAZ150CF','BGL',150.0,1.0,0.995,1.005,0.955,0.95,0.96,3.0,2.8,3.0,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10060',60,'BGLSAZ150CF','BGL',150.0,1.2,1.195,1.205,1.155,1.15,1.16,3.2,2.8,3.2,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10061',61,'BGLSAZ150CF','BGL',150.0,1.4,1.395,1.405,1.355,1.35,1.36,3.6,3.2,4.0,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10062',62,'BGLSAZ150CF','BGL',150.0,1.6,1.595,1.605,1.555,1.55,1.56,4.0,3.2,4.0,'REVIEW','Duplicate business key',false);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10063',63,'CRFHCF','CR',NULL,NULL,NULL,NULL,0.46,0.455,0.46,2.5,2.2,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10064',64,'CRFHCF','CR',NULL,NULL,NULL,NULL,0.48,0.475,0.48,2.5,2.2,2.8,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10065',65,'CRFHCF','CR',NULL,NULL,NULL,NULL,0.85,0.84,0.85,2.5,2.0,2.8,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10066',66,'CRFHCF','CR',NULL,NULL,NULL,NULL,0.33,0.32,0.34,2.0,1.8,2.2,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10067',67,'CRFHCF','CR',NULL,NULL,NULL,NULL,0.55,0.54,0.56,2.5,2.0,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10068',68,'CRFHCF','CR',NULL,NULL,NULL,NULL,0.51,0.5,0.52,2.5,2.0,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10069',69,'CRFHCF','CR',NULL,NULL,NULL,NULL,0.28,0.27,0.29,2.2,2.0,2.2,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10070',70,'CRFHCF','CR',NULL,NULL,NULL,NULL,0.38,0.37,0.39,2.2,2.0,2.2,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10071',71,'CRFHCF','CR',NULL,NULL,NULL,NULL,0.6,0.59,0.61,2.5,2.0,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10072',72,'CRFHCF','CR',NULL,NULL,NULL,NULL,0.9,0.89,0.91,2.8,2.5,3.0,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10073',73,'CRFHCF','CR',NULL,NULL,NULL,NULL,0.89,0.88,0.9,2.8,2.5,3.0,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10074',74,'BGLAZ150CF','BGL',150.0,0.7,0.695,0.705,0.66,0.655,0.665,2.5,2.2,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10075',75,'BGLAZ150CF','BGL',150.0,0.9,0.895,0.905,0.855,0.845,0.86,2.8,2.5,2.8,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10076',76,'BGLAZ70CF','BGL',70.0,0.7,0.695,0.705,0.665,0.66,0.67,2.5,2.2,2.8,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10077',77,'BGLAZ70CF','BGL',70.0,0.8,0.795,0.805,0.765,0.76,0.77,2.5,2.2,2.8,'REVIEW','Duplicate business key',false);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10078',78,'BGLAZ70CF','BGL',70.0,0.9,0.895,0.905,0.865,0.86,0.87,2.8,2.5,3.0,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10079',79,'BGLAZ70CF','BGL',70.0,1.0,0.995,1.005,0.96,0.96,0.97,2.8,2.5,3.0,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10080',80,'BGLAZ70CF','BGL',70.0,1.2,1.195,1.205,1.165,1.16,1.17,2.8,2.5,3.0,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10081',81,'GLAZ70CFPR','GL',70.0,0.45,0.445,0.455,0.43,0.425,0.435,2.5,2.2,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10082',82,'BGLAZ150CF','BGL',150.0,0.5,0.495,0.505,0.43,0.425,0.435,2.5,2.2,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10083',83,'BGLSAZ150CF','BGL',150.0,0.95,0.945,0.955,0.905,0.9,0.91,2.8,2.5,3.0,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10084',84,'BGLOEAZ150CF','BGL',150.0,0.5,0.5,0.5,0.455,0.45,0.46,2.5,2.0,2.5,'REVIEW','Duplicate business key',false);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10085',85,'BGLAZ150CF','BGL',150.0,1.2,1.195,1.205,1.155,1.55,1.16,3.0,2.8,3.2,'REVIEW','CR Min > Max; CR target outside Min/Max',false);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10086',86,'BGLAZ150CF','BGL',150.0,1.4,1.395,1.405,1.355,1.35,1.36,4.0,3.5,4.0,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10087',87,'BGLOEAZ150CF','BGL',150.0,0.5,0.495,0.505,0.455,0.45,0.46,2.0,1.6,2.2,'REVIEW','Duplicate business key',false);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10088',88,'GLAZ70CF','GL',70.0,0.27,0.265,0.275,0.245,0.24,0.25,2.0,1.6,2.2,'REVIEW','Duplicate business key',false);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10089',89,'BGLSAZ150CF','BGL',150.0,1.5,1.45,1.55,1.455,1.405,1.505,4.0,3.8,4.2,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10090',90,'BGLOEAZ150CF','BGL',150.0,0.5,0.5,0.5,0.455,0.45,0.46,2.5,2.0,2.5,'REVIEW','Duplicate business key',false);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10091',91,'BGLOEAZ150CF','BGL',150.0,0.9,0.9,0.9,0.855,0.85,0.86,2.8,2.5,2.8,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10092',92,'BGLAZ70CF','BGL',70.0,1.4,1.395,1.405,1.36,1.36,1.36,3.5,3.2,4.0,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10093',93,'BGLAZ70CF','BGL',70.0,1.5,1.495,1.505,1.465,1.46,1.47,3.5,3.2,4.0,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10094',94,'BGLAZ70CF','BGL',70.0,1.6,1.595,1.605,1.565,1.56,1.57,3.5,3.2,4.0,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10095',95,'BGLAZ70CF','BGL',70.0,0.42,0.42,0.42,0.35,0.35,0.35,2.2,2.0,2.2,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10096',96,'GLAZ150CF','GL',150.0,0.47,0.47,0.47,0.43,0.43,0.43,2.2,2.0,2.2,'REVIEW','Duplicate business key',false);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10097',97,'BGLAZ70CF','BGL',70.0,1.35,1.3,1.4,1.31,1.26,1.36,3.0,2.8,3.6,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10098',98,NULL,NULL,70.0,1.15,1.1,1.2,1.11,1.06,1.16,3.0,2.8,3.6,'REVIEW','Missing/invalid Material or ProductGroup',false);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10099',99,'CRFHCF','CR',NULL,NULL,NULL,NULL,0.44,0.39,0.049,2.5,2.0,2.8,'REVIEW','CR Min > Max; CR target outside Min/Max',false);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10100',100,'BGLOEAZ150CF','BGL',150.0,0.47,0.42,0.52,0.425,0.375,0.475,2.5,2.2,2.8,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10102',101,'GLAZ150CF','GL',150.0,0.57,0.52,0.62,0.53,0.48,0.58,2.5,2.2,2.8,'REVIEW','Duplicate business key',false);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10103',102,'GLAZ100CF','GL',100.0,0.37,0.32,0.42,0.33,0.28,0.38,2.2,2.0,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10104',103,'BGLOEAZ70CF','BGL',70.0,0.6,0.55,0.65,0.56,0.51,0.61,2.5,2.2,2.8,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10105',104,'BGLAZ150CF','BGL',150.0,1.0,0.95,1.05,0.955,0.905,1.005,2.8,2.5,3.2,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10106',105,'BGLOEAZ150CF','BGL',150.0,0.55,0.55,0.55,0.505,0.505,0.505,2.8,2.5,2.8,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10107',106,'GLAZ150CF','GL',150.0,0.47,0.42,0.52,0.43,0.38,0.48,2.2,2.0,2.5,'REVIEW','Duplicate business key',false);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10108',107,'GLAZ70CF','GL',70.0,0.45,0.45,0.45,0.435,0.435,0.435,2.5,2.2,2.0,'REVIEW','HR Min > Max; HR target outside Min/Max',false);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10109',108,'GLAZ70CF','GL',70.0,0.55,0.55,0.55,0.535,0.535,0.535,2.5,2.2,2.0,'REVIEW','HR Min > Max; HR target outside Min/Max',false);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10110',109,'BGLOEAZ70CF','BGL',70.0,0.5,0.495,0.505,0.475,0.47,0.48,2.5,2.0,2.8,'REVIEW','Duplicate business key',false);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10111',110,'BGLOEAZ70CF','BGL',70.0,0.35,0.345,0.355,0.325,0.32,0.33,2.2,2.0,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10112',111,'BGLAZ150CF','BGL',150.0,0.45,0.4,0.5,0.38,0.33,0.43,2.2,2.0,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10113',112,'BGLAZ150CF','BGL',150.0,0.47,0.42,0.52,0.4,0.35,0.45,2.2,2.0,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10114',113,'GLAZ70CF','GL',70.0,0.38,0.33,0.43,0.36,0.31,0.41,2.2,2.0,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10115',114,'BGLAZ70CF','BGL',70.0,0.6,0.55,0.65,0.53,0.48,0.58,2.5,2.0,2.8,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10116',115,'GLAZ70CF','GL',70.0,0.28,0.275,0.285,0.26,0.265,0.255,2.2,2.0,2.5,'REVIEW','CR Min > Max; CR target outside Min/Max',false);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10117',116,'GLAZ70CF','GL',70.0,0.32,0.315,0.325,0.3,0.295,0.305,2.0,1.6,2.2,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10118',117,'GLAZ70CFPR','GL',70.0,0.67,0.665,0.675,0.65,0.645,0.655,2.5,2.2,2.8,'REVIEW','Duplicate business key',false);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10119',118,'GLAZ70CFPR','GL',70.0,0.42,0.415,0.425,0.395,0.39,0.4,2.2,2.0,2.5,'REVIEW','Duplicate business key',false);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10120',119,'CRFHCF','CR',NULL,NULL,NULL,NULL,0.24,0.235,0.245,2.2,2.0,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10121',120,'BGLAZ70CF','BGL',70.0,0.8,0.795,0.805,0.77,0.765,0.775,2.8,2.5,3.0,'REVIEW','Duplicate business key',false);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10122',121,'BGLSAZ150CF','BGL',150.0,0.9,0.9,0.9,0.855,0.855,0.855,2.8,3.0,2.8,'REVIEW','HR Min > Max; HR target outside Min/Max; Duplicate business key',false);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10123',122,'BGLSAZ150CF','BGL',150.0,1.6,1.6,1.6,1.155,1.155,1.155,2.8,3.0,3.8,'REVIEW','HR target outside Min/Max; Duplicate business key',false);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10124',123,'BGLPTAZ70CF','BGL',70.0,1.35,1.345,1.355,1.32,1.315,1.325,3.6,3.2,4.0,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10125',124,'BGLPTAZ70CF','BGL',70.0,1.15,1.145,1.155,1.12,1.115,1.125,3.0,2.8,3.2,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10126',125,'CRFHCF','CR',NULL,NULL,NULL,NULL,0.4,0.395,0.405,2.2,2.0,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10127',126,'CRFHCF','CR',NULL,NULL,NULL,NULL,0.27,0.265,0.275,2.2,2.0,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10128',127,'CRFHCF','CR',NULL,NULL,NULL,NULL,0.26,0.255,0.265,2.2,2.0,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10129',128,'BGLPTAZ70CF','BGL',70.0,0.9,0.895,0.905,0.855,0.85,0.86,2.8,2.8,3.2,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10130',129,'CRFHCF','CR',NULL,NULL,NULL,NULL,0.95,0.945,0.955,2.8,2.5,3.0,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10131',130,'CRFHCF','CR',NULL,NULL,NULL,NULL,1.15,1.145,1.155,3.0,2.8,3.2,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10132',131,'CRFHCF','CR',NULL,NULL,NULL,NULL,1.35,1.345,1.355,3.0,2.8,3.2,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10133',132,'CRFHCF','CR',NULL,NULL,NULL,NULL,1.55,1.545,1.555,3.6,3.2,4.0,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10134',133,'BGLPTAZ70CF','BGL',70.0,1.2,1.15,1.25,1.155,1.105,1.205,2.8,3.0,3.2,'REVIEW','HR target outside Min/Max',false);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10135',134,'BGLPTAZ70CF','BGL',70.0,1.4,1.35,1.45,1.36,1.31,1.41,3.6,3.2,4.0,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10136',135,'BGLAZ185CF','BGL',185.0,0.55,0.55,0.55,0.49,0.49,0.49,2.5,2.8,3.0,'REVIEW','HR target outside Min/Max',false);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10137',136,'BGLAZ185CF','BGL',185.0,0.75,0.75,0.75,0.69,0.69,0.69,2.5,2.8,3.0,'REVIEW','HR target outside Min/Max',false);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10138',137,'BGLOEAZ150CF','BGL',150.0,1.15,1.145,1.155,1.105,1.1,1.11,3.0,2.8,3.6,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10139',138,'BGLPTAZ70CF','BGL',70.0,1.0,0.995,1.005,0.96,0.955,0.965,3.0,2.8,3.6,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10140',139,'CRFHCF','CR',NULL,NULL,NULL,NULL,0.41,0.405,0.415,2.2,2.0,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10141',140,'HRPOCF','HR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,3.0,2.8,3.2,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10142',141,'GLAZ100CF','GL',100.0,0.35,0.345,0.355,0.33,0.325,0.335,2.2,2.0,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10143',142,'GLAZ150CF','GL',150.0,0.56,0.555,0.565,0.52,0.515,0.525,2.2,2.0,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10144',143,'CRFHCF','CR',NULL,NULL,NULL,NULL,0.8,0.795,0.805,2.8,2.5,3.0,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10145',144,'GLAZ150CF','GL',150.0,0.52,0.515,0.525,0.48,0.475,0.485,2.5,2.0,2.8,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10146',145,'CRFHCF','CR',NULL,NULL,NULL,NULL,0.25,0.2,0.3,2.0,1.6,2.2,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10147',146,'GLAZ150CF','GL',150.0,0.46,0.455,0.465,0.42,0.415,0.425,2.5,2.2,2.8,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10148',147,'GLAZ150CF','GL',150.0,0.34,0.345,0.335,0.3,0.295,0.305,2.2,2.0,2.5,'REVIEW','GL Min > Max; GL target outside Min/Max',false);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10149',148,'BGLPTAZ70CF','BGL',70.0,1.6,1.595,1.605,1.56,1.555,1.565,3.2,3.0,3.6,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10150',149,'BGLPTAZ70CF','BGL',70.0,0.8,0.795,0.805,0.76,0.755,0.765,2.8,2.8,3.0,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10151',150,'GLAZ70CF','GL',70.0,0.41,0.405,0.415,0.39,0.385,0.395,2.2,2.0,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10152',151,'BGLOEAZ70CF','BGL',70.0,0.8,0.795,0.805,0.78,0.775,0.785,2.8,2.5,3.0,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10153',152,'BGLOEAZ70CF','BGL',70.0,1.0,0.995,1.005,0.98,0.975,0.985,2.8,2.5,3.0,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10154',153,'GLAZ70APSPCF','GL',70.0,0.29,0.285,0.295,0.28,0.275,0.285,2.0,1.6,2.2,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10155',154,'GLAZ70APSPCF','GL',70.0,0.35,0.345,0.355,0.34,0.335,0.345,2.2,2.0,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10156',155,'GLAZ70APSPCF','GL',70.0,0.38,0.375,0.385,0.36,0.355,0.365,2.2,2.0,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10157',156,'GLAZ70APSPCF','GL',70.0,0.39,0.385,0.395,0.38,0.375,0.385,2.2,2.0,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10158',157,'GLAZ70APSPCF','GL',70.0,0.41,0.405,0.415,0.4,0.395,0.405,2.2,2.0,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10159',158,'BGLSAZ165CF','BGL',165.0,1.2,1.195,1.205,1.15,1.145,1.16,3.0,2.8,3.2,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10160',159,'BGLPTAZ70CF','BGL',70.0,1.5,1.45,1.55,1.46,1.455,1.65,3.2,3.0,3.6,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10161',160,'BGLOEAZ70CF','BGL',70.0,0.4,0.4,0.4,0.375,0.375,0.375,2.0,2.2,2.5,'REVIEW','HR target outside Min/Max',false);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10162',161,'BGLOEAZ70CF','BGL',70.0,0.5,0.5,0.5,0.475,0.475,0.475,2.0,2.2,2.5,'REVIEW','HR target outside Min/Max; Duplicate business key',false);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10163',162,'BGLOEAZ70CF','BGL',70.0,0.45,0.45,0.45,0.43,0.43,0.43,2.0,2.2,2.5,'REVIEW','HR target outside Min/Max',false);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10164',163,'GLAZ70CF','GL',70.0,0.34,0.335,0.345,0.32,0.315,0.325,2.2,2.0,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10165',164,'CRFHCF','CR',NULL,NULL,NULL,NULL,0.3,0.295,0.305,2.2,2.0,2.5,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10166',165,'BGLSAZ165CF','BGL',165.0,0.9,0.895,0.905,0.85,0.845,0.855,3.0,2.8,3.2,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10167',166,'BGLSAZ200CF','BGL',200.0,1.2,1.195,1.205,1.14,1.155,1.165,3.0,2.8,3.2,'REVIEW','CR target outside Min/Max',false);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10168',167,'BGLSAZ200CF','BGL',200.0,1.6,1.57,1.63,1.54,1.535,1.545,3.6,3.2,3.6,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10169',168,'BGLSAZ150CF','BGL',150.0,0.8,0.795,0.805,0.755,0.75,0.76,3.0,2.8,3.2,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10170',169,'BGLAZ150CF','BGL',150.0,1.5,1.495,1.505,1.455,1.45,1.46,3.2,3.0,3.6,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10171',170,'HRPOCF','HR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,2.0,2.0,2.0,'VALID',NULL,true);
INSERT INTO mes.planning_thickness_matrix (plant_code,source_uuid,source_row_no,material_code,product_group,coating_gsm,finished_thk_target_mm,finished_thk_min_mm,finished_thk_max_mm,cr_thk_target_mm,cr_thk_min_mm,cr_thk_max_mm,hr_thk_target_mm,hr_thk_min_mm,hr_thk_max_mm,validation_status,validation_notes,is_active) VALUES ('2000','10172',171,'HRPOCF','HR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,2.5,2.5,2.5,'VALID',NULL,true);

COMMIT;

-- Verification
SELECT plant_code, validation_status, is_active, count(*)
FROM mes.planning_thickness_matrix
WHERE plant_code='2000'
GROUP BY plant_code, validation_status, is_active
ORDER BY validation_status, is_active;

-- The bad source row is intentionally retained as REVIEW/inactive rather than aborting the load.
SELECT source_row_no, source_uuid, material_code, product_group, coating_gsm,
       validation_status, is_active, validation_notes
FROM mes.planning_thickness_matrix
WHERE plant_code='2000' AND source_row_no=98;

SELECT count(*) AS total_matrix_rows
FROM mes.planning_thickness_matrix
WHERE plant_code='2000';