-- ============================================================================
-- COLORSHINE MES V2 v0.9.7
-- 27_rm_inventory_v097_cleanup_performance.sql
--
-- Purpose
--   * Add a safe cleanup function for the approved RM opening migration.
--   * Speed up Screen 1102 by removing the per-row QA LATERAL aggregation.
--   * Add indexes used by RM inventory, QA and filter queries.
--   * Standardize Screen 1102 source formatting:
--       thickness = 3 decimals, width = whole mm, chemistry = 3 decimals,
--       RM source shown without leading zeroes.
--   * Preserve stock-generated date / stock-age fields from GRN posting date.
--
-- NOTE
--   Random 2025 -> current-date posting dates are generated by the v0.9.7
--   rebuild script and written into the canonical goods_receipt posting_date.
-- ============================================================================

SET search_path TO mes, public;
BEGIN;

-- --------------------------------------------------------------------------
-- A. Performance indexes
-- --------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS ix_rm_tc_result_supplier_parameter
    ON mes.rm_supplier_tc_result(supplier_tc_id, parameter_id);

CREATE INDEX IF NOT EXISTS ix_rm_supplier_tc_batch_id
    ON mes.rm_supplier_tc(batch_id);

CREATE INDEX IF NOT EXISTS ix_rm_supplier_tc_plant_batch
    ON mes.rm_supplier_tc(plant_code, batch_no);

CREATE INDEX IF NOT EXISTS ix_rm_inventory_balance_plant_batch
    ON mes.rm_inventory_balance(plant_code, batch_id);

CREATE INDEX IF NOT EXISTS ix_rm_inventory_balance_plant_storage
    ON mes.rm_inventory_balance(plant_code, storage_location, batch_id);

CREATE INDEX IF NOT EXISTS ix_grn_coil_batch_plant
    ON mes.goods_receipt_coil(batch_id, plant_code);

CREATE INDEX IF NOT EXISTS ix_grn_coil_material_plant
    ON mes.goods_receipt_coil(material_id, plant_code);

CREATE INDEX IF NOT EXISTS ix_goods_receipt_plant_posting
    ON mes.goods_receipt(plant_code, posting_date DESC, sap_grn_no);

CREATE INDEX IF NOT EXISTS ix_batch_master_material_active
    ON mes.batch_master(material_id, lifecycle_status, batch_no);

-- --------------------------------------------------------------------------
-- B. Safe cleanup function for previous opening migrations only.
--    It does not touch normal future SAP/live GRNs.
-- --------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION mes.cleanup_rm_opening_migration()
RETURNS TABLE(
    deleted_batches integer,
    deleted_grn_coils integer,
    deleted_grn_headers integer,
    deleted_upload_runs integer
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_batches integer := 0;
    v_coils integer := 0;
    v_grns integer := 0;
    v_runs integer := 0;
BEGIN
    CREATE TEMP TABLE tmp_rm_opening_batches(batch_id uuid PRIMARY KEY) ON COMMIT DROP;
    CREATE TEMP TABLE tmp_rm_opening_grns(grn_id uuid PRIMARY KEY) ON COMMIT DROP;

    INSERT INTO tmp_rm_opening_batches(batch_id)
    SELECT DISTINCT u.linked_batch_id
      FROM mes.rm_opening_inventory_upload u
      JOIN mes.rm_opening_inventory_upload_run r ON r.upload_run_id=u.upload_run_id
     WHERE u.linked_batch_id IS NOT NULL
       AND (r.upload_name LIKE 'APPROVED_RM_OPENING_%' OR COALESCE(r.source_file_name,'') ILIKE '%RM_GRN_Dump%')
    ON CONFLICT DO NOTHING;

    INSERT INTO tmp_rm_opening_batches(batch_id)
    SELECT DISTINCT c.batch_id
      FROM mes.goods_receipt_coil c
     WHERE c.batch_id IS NOT NULL
       AND COALESCE(c.source_row_key,'') LIKE 'OPENING:%'
    ON CONFLICT DO NOTHING;

    INSERT INTO tmp_rm_opening_grns(grn_id)
    SELECT DISTINCT c.grn_id
      FROM mes.goods_receipt_coil c
      JOIN tmp_rm_opening_batches b ON b.batch_id=c.batch_id
     WHERE c.grn_id IS NOT NULL
    ON CONFLICT DO NOTHING;

    SELECT count(*)::int INTO v_batches FROM tmp_rm_opening_batches;
    SELECT count(*)::int INTO v_coils
      FROM mes.goods_receipt_coil c JOIN tmp_rm_opening_batches b ON b.batch_id=c.batch_id;

    DELETE FROM mes.rm_usage_decision u
     USING tmp_rm_opening_batches b
     WHERE u.batch_id=b.batch_id;

    DELETE FROM mes.rm_quality_inspection q
     USING tmp_rm_opening_batches b
     WHERE q.batch_id=b.batch_id;

    DELETE FROM mes.rm_supplier_tc tc
     USING tmp_rm_opening_batches b
     WHERE tc.batch_id=b.batch_id;

    DELETE FROM mes.rm_inventory_movement mv
     USING tmp_rm_opening_batches b
     WHERE mv.batch_id=b.batch_id;

    DELETE FROM mes.rm_inventory_balance ib
     USING tmp_rm_opening_batches b
     WHERE ib.batch_id=b.batch_id;

    DELETE FROM mes.goods_receipt_coil c
     USING tmp_rm_opening_batches b
     WHERE c.batch_id=b.batch_id;

    DELETE FROM mes.batch_master bm
     USING tmp_rm_opening_batches b
     WHERE bm.batch_id=b.batch_id;

    DELETE FROM mes.goods_receipt g
     USING tmp_rm_opening_grns t
     WHERE g.grn_id=t.grn_id
       AND NOT EXISTS (SELECT 1 FROM mes.goods_receipt_coil c WHERE c.grn_id=g.grn_id);
    GET DIAGNOSTICS v_grns = ROW_COUNT;

    DELETE FROM mes.rm_opening_inventory_upload_run r
     WHERE r.upload_name LIKE 'APPROVED_RM_OPENING_%'
        OR COALESCE(r.source_file_name,'') ILIKE '%RM_GRN_Dump%';
    GET DIAGNOSTICS v_runs = ROW_COUNT;

    -- QA staging is migration reference data only. Rebuild script reloads it cleanly.
    DELETE FROM mes.rm_qa_reference_stage;

    RETURN QUERY SELECT v_batches,v_coils,v_grns,v_runs;
END;
$$;

-- --------------------------------------------------------------------------
-- C. Canonical RM Stores view - optimized QA aggregation.
--    The old view executed one QA aggregate subquery per coil. This version scans
--    rm_supplier_tc_result once and joins the aggregate by supplier_tc_id.
-- --------------------------------------------------------------------------
DROP VIEW IF EXISTS mes.vw_plant_stock_report;
DROP VIEW IF EXISTS mes.vw_rm_store_inventory;

CREATE VIEW mes.vw_rm_store_inventory AS
WITH qa AS (
    SELECT
      r.supplier_tc_id,
      round(max(r.numeric_value) FILTER (WHERE p.parameter_code='CARBON_PCT'),3) AS carbon,
      round(max(r.numeric_value) FILTER (WHERE p.parameter_code='MANGANESE_PCT'),3) AS manganese,
      round(max(r.numeric_value) FILTER (WHERE p.parameter_code='SULPHUR_PCT'),3) AS sulphur,
      round(max(r.numeric_value) FILTER (WHERE p.parameter_code='PHOSPHORUS_PCT'),3) AS phosphorus,
      round(max(r.numeric_value) FILTER (WHERE p.parameter_code='SILICON_PCT'),3) AS silicon,
      round(max(r.numeric_value) FILTER (WHERE p.parameter_code='ALUMINIUM_PCT'),3) AS aluminium,
      round(max(r.numeric_value) FILTER (WHERE p.parameter_code='CARBON_EQ'),3) AS carbon_equivalent,
      round(COALESCE(
        max(r.numeric_value) FILTER (WHERE p.parameter_code='NITROGEN_PPM'),
        max(r.numeric_value) FILTER (WHERE p.parameter_code='NITROGEN_PCT')
      ),3) AS nitrogen,
      round(max(r.numeric_value) FILTER (WHERE p.parameter_code='COPPER_PCT'),3) AS copper,
      round(max(r.numeric_value) FILTER (WHERE p.parameter_code='CHROMIUM_PCT'),3) AS chromium,
      round(max(r.numeric_value) FILTER (WHERE p.parameter_code='NICKEL_PCT'),3) AS nickel
    FROM mes.rm_supplier_tc_result r
    JOIN mes.quality_parameter_master p ON p.parameter_id=r.parameter_id
    WHERE p.parameter_code IN (
      'CARBON_PCT','MANGANESE_PCT','SULPHUR_PCT','PHOSPHORUS_PCT','SILICON_PCT',
      'ALUMINIUM_PCT','CARBON_EQ','NITROGEN_PPM','NITROGEN_PCT','COPPER_PCT',
      'CHROMIUM_PCT','NICKEL_PCT'
    )
    GROUP BY r.supplier_tc_id
)
SELECT
    ('LIVE:'||ib.inventory_balance_id::text) AS row_id,
    'LIVE_MES'::varchar(30) AS source_system,
    NULL::integer AS source_row_no,
    'CANONICAL_RM'::varchar(120) AS source_file,
    COALESCE(m.material_type,'HR')::varchar(20) AS material_type,
    'RM'::varchar(10) AS stock_stage,
    ib.plant_code,
    ib.storage_location,
    m.sap_material_code AS material_code,
    m.material_description,
    COALESCE(c.product_group,m.product_group) AS product_group,
    COALESCE(c.product_type,m.product_type,'COIL') AS product_type,
    b.batch_no,
    ib.on_hand_weight_mt::numeric(14,4) AS batch_qty_mt,
    COALESCE(NULLIF(tc.quality_level,''),
             CASE b.quality_status WHEN 'ACCEPTED' THEN 'PRIME' WHEN 'REJECTED' THEN 'REJECT' ELSE 'PENDING_QA' END) AS qa_grade,
    ib.stock_status,
    round(c.batch_thickness_mm::numeric,3)::numeric(12,3) AS thickness_mm,
    round(c.batch_width_mm::numeric,0)::numeric(12,0) AS width_mm,
    tc.batch_length_m AS length_value,
    NULL::varchar(40) AS temper,
    NULL::varchar(40) AS coating,
    NULL::varchar(80) AS jet_printing,
    g.posting_date AS stock_generated_date,
    CASE WHEN g.posting_date IS NULL THEN NULL ELSE CURRENT_DATE-g.posting_date END AS stock_age_days,
    COALESCE(NULLIF(ltrim(COALESCE(c.rm_source,''),'0'),''),'0')::varchar(40) AS rm_source,
    g.sap_grn_no,
    c.sap_po_no,
    c.sap_po_item,
    c.po_delivery_date,
    c.movement_type,
    c.equivalent_spec AS eq_spec,
    c.eq_spec_group,
    c.eq_sub_spec,
    c.chapter_id,
    c.chapter_type,
    c.crown,
    b.batch_no AS mother_rm_batch,
    c.vendor_batch_no AS supplier_batch,
    tc.heat_no,
    g.posting_date AS mother_stock_grn_date,
    CASE WHEN g.posting_date IS NULL THEN NULL ELSE CURRENT_DATE-g.posting_date END AS mother_stock_grn_age_days,
    tc.hr_grade AS rm_steel_grade,
    qa.carbon::text AS carbon,
    qa.manganese::text AS manganese,
    qa.sulphur::text AS sulphur,
    qa.phosphorus::text AS phosphorus,
    qa.silicon::text AS silicon,
    qa.aluminium::text AS aluminium,
    qa.carbon_equivalent::text AS carbon_equivalent,
    qa.nitrogen::text AS nitrogen,
    qa.copper::text AS copper,
    NULL::text AS molybdenum,
    qa.chromium::text AS chromium,
    qa.nickel::text AS nickel,
    COALESCE(s.supplier_name,c.source_supplier_name)::varchar(200) AS rm_supplier,
    b.created_at AS imported_at,
    GREATEST(ib.updated_at,b.updated_at,COALESCE(tc.updated_at,'1900-01-01'::timestamptz)) AS updated_at
FROM mes.rm_inventory_balance ib
JOIN mes.batch_master b ON b.batch_id=ib.batch_id
JOIN mes.material_master m ON m.material_id=b.material_id
LEFT JOIN mes.goods_receipt_coil c ON c.batch_id=b.batch_id AND c.plant_code=ib.plant_code
LEFT JOIN mes.goods_receipt g ON g.grn_id=c.grn_id
LEFT JOIN mes.supplier_master s ON s.supplier_id=c.supplier_id
LEFT JOIN mes.rm_supplier_tc tc ON tc.batch_id=b.batch_id
LEFT JOIN qa ON qa.supplier_tc_id=tc.supplier_tc_id
WHERE m.sap_material_code LIKE 'R_HR%';

-- Complete Plant Stock Report source remains compatible with previous design.
CREATE VIEW mes.vw_plant_stock_report AS
SELECT
  row_id AS inventory_id,source_row_no,source_file,material_type,stock_stage,plant_code,storage_location,
  material_code,batch_no,batch_qty_mt,qa_grade,thickness_mm,width_mm,length_value,
  temper,coating,jet_printing,stock_generated_date,stock_age_days,
  NULL::varchar(40) AS mes_po,NULL::varchar(20) AS so_no,NULL::varchar(10) AS so_line_item,
  NULL::numeric(10,4) AS so_thickness_mm,NULL::numeric(12,3) AS so_width_mm,NULL::varchar(40) AS so_temper,
  NULL::varchar(40) AS so_quality,NULL::varchar(40) AS so_coating,NULL::numeric(14,4) AS so_min_wt_mt,
  NULL::numeric(14,4) AS so_max_wt_mt,NULL::varchar(100) AS so_logo,NULL::varchar(100) AS so_spangle,
  NULL::varchar(100) AS so_jet_printing,NULL::varchar(100) AS so_tll,
  mother_rm_batch,supplier_batch,heat_no,mother_stock_grn_date,mother_stock_grn_age_days,
  rm_steel_grade,carbon,manganese,sulphur,phosphorus,silicon,aluminium,carbon_equivalent,
  nitrogen,copper,molybdenum,chromium,nickel,rm_supplier,imported_at,updated_at
FROM mes.vw_rm_store_inventory
UNION ALL
SELECT
  inventory_id::text,source_row_no,source_file,material_type,stock_stage,plant_code,storage_location,
  material_code,batch_no,batch_qty_mt,qa_grade,thickness_mm,width_mm,length_value,
  temper,coating,jet_printing,stock_generated_date,stock_age_days,
  mes_po,so_no,so_line_item,so_thickness_mm,so_width_mm,so_temper,so_quality,
  so_coating,so_min_wt_mt,so_max_wt_mt,so_logo,so_spangle,so_jet_printing,so_tll,
  mother_rm_batch,supplier_batch,heat_no,mother_stock_grn_date,mother_stock_grn_age_days,
  rm_steel_grade,carbon,manganese,sulphur,phosphorus,silicon,aluminium,carbon_equivalent,
  nitrogen,copper,molybdenum,chromium,nickel,rm_supplier,imported_at,updated_at
FROM mes.inventory_master
WHERE UPPER(COALESCE(stock_stage,'')) IN ('WIP','FG');

-- Normalize the vendor/source code on the GRN Monitor as well, preserving type.
CREATE OR REPLACE VIEW mes.vw_grn_ud_queue AS
SELECT
    c.grn_coil_id,
    c.batch_id,
    g.plant_code,
    g.sap_grn_no,
    g.sap_material_doc_year,
    g.posting_date AS grn_posting_date,
    c.sap_po_no,
    c.sap_po_item,
    c.storage_location,
    COALESCE(NULLIF(ltrim(COALESCE(s.sap_vendor_no,c.rm_source,''),'0'),''),'0')::varchar(20) AS sap_vendor_no,
    COALESCE(s.supplier_name,c.source_supplier_name)::varchar(200) AS supplier_name,
    m.sap_material_code,
    m.material_description,
    c.batch_no,
    c.vendor_batch_no,
    c.batch_thickness_mm,
    c.batch_width_mm,
    c.batch_weight_mt,
    tc.supplier_tc_no,
    tc.heat_no,
    tc.hr_grade,
    tc.quality_level,
    b.quality_status,
    q.inspection_no,
    q.inspection_status,
    q.overall_result,
    u.ud_no,
    u.decision AS current_ud,
    u.decided_by,
    u.decided_at,
    COALESCE(inv.quality_hold_weight_mt,0) AS quality_hold_weight_mt,
    COALESCE(inv.available_weight_mt,0) AS available_weight_mt,
    COALESCE(inv.blocked_weight_mt,0) AS blocked_weight_mt
FROM mes.goods_receipt_coil c
JOIN mes.goods_receipt g ON g.grn_id=c.grn_id
JOIN mes.batch_master b ON b.batch_id=c.batch_id
JOIN mes.material_master m ON m.material_id=c.material_id
LEFT JOIN mes.supplier_master s ON s.supplier_id=c.supplier_id
LEFT JOIN mes.rm_supplier_tc tc ON tc.batch_id=c.batch_id
LEFT JOIN LATERAL (
    SELECT qi.* FROM mes.rm_quality_inspection qi
     WHERE qi.batch_id=c.batch_id
     ORDER BY qi.inspection_sequence DESC,qi.created_at DESC LIMIT 1
) q ON true
LEFT JOIN mes.rm_usage_decision u ON u.batch_id=c.batch_id AND u.is_current=true
LEFT JOIN LATERAL (
    SELECT sum(ib.quality_hold_weight_mt) AS quality_hold_weight_mt,
           sum(ib.available_weight_mt) AS available_weight_mt,
           sum(ib.blocked_weight_mt) AS blocked_weight_mt
      FROM mes.rm_inventory_balance ib WHERE ib.batch_id=c.batch_id
) inv ON true;

COMMIT;
