-- Colorshine MES v0.11.4 - Plant Stock Report: expose live batch/stock status
-- Scope: Company 2000 / Plant 2000
--
-- vw_rm_store_inventory already computes ib.stock_status (AVAILABLE / QUALITY_HOLD /
-- BLOCKED / PART_RESERVED for RM) but vw_plant_stock_report never projected it.
-- Appended at the end (CREATE OR REPLACE VIEW cannot insert a column mid-list).
-- WIP/FG rows come from the static inventory_master import table, which has no
-- live status tracking yet, so they show NULL until that module exists.

CREATE OR REPLACE VIEW mes.vw_plant_stock_report AS
 SELECT vw_rm_store_inventory.row_id AS inventory_id,
    vw_rm_store_inventory.source_row_no,
    vw_rm_store_inventory.source_file,
    vw_rm_store_inventory.material_type,
    vw_rm_store_inventory.stock_stage,
    vw_rm_store_inventory.plant_code,
    vw_rm_store_inventory.storage_location,
    vw_rm_store_inventory.material_code,
    vw_rm_store_inventory.batch_no,
    vw_rm_store_inventory.batch_qty_mt,
    vw_rm_store_inventory.qa_grade,
    vw_rm_store_inventory.thickness_mm,
    vw_rm_store_inventory.width_mm,
    vw_rm_store_inventory.length_value,
    vw_rm_store_inventory.temper,
    vw_rm_store_inventory.coating,
    vw_rm_store_inventory.jet_printing,
    vw_rm_store_inventory.stock_generated_date,
    vw_rm_store_inventory.stock_age_days,
    NULL::character varying(40) AS mes_po,
    NULL::character varying(20) AS so_no,
    NULL::character varying(10) AS so_line_item,
    NULL::numeric(10,4) AS so_thickness_mm,
    NULL::numeric(12,3) AS so_width_mm,
    NULL::character varying(40) AS so_temper,
    NULL::character varying(40) AS so_quality,
    NULL::character varying(40) AS so_coating,
    NULL::numeric(14,4) AS so_min_wt_mt,
    NULL::numeric(14,4) AS so_max_wt_mt,
    NULL::character varying(100) AS so_logo,
    NULL::character varying(100) AS so_spangle,
    NULL::character varying(100) AS so_jet_printing,
    NULL::character varying(100) AS so_tll,
    vw_rm_store_inventory.mother_rm_batch,
    vw_rm_store_inventory.supplier_batch,
    vw_rm_store_inventory.heat_no,
    vw_rm_store_inventory.mother_stock_grn_date,
    vw_rm_store_inventory.mother_stock_grn_age_days,
    vw_rm_store_inventory.rm_steel_grade,
    vw_rm_store_inventory.carbon,
    vw_rm_store_inventory.manganese,
    vw_rm_store_inventory.sulphur,
    vw_rm_store_inventory.phosphorus,
    vw_rm_store_inventory.silicon,
    vw_rm_store_inventory.aluminium,
    vw_rm_store_inventory.carbon_equivalent,
    vw_rm_store_inventory.nitrogen,
    vw_rm_store_inventory.copper,
    vw_rm_store_inventory.molybdenum,
    vw_rm_store_inventory.chromium,
    vw_rm_store_inventory.nickel,
    vw_rm_store_inventory.rm_supplier,
    vw_rm_store_inventory.imported_at,
    vw_rm_store_inventory.updated_at,
    vw_rm_store_inventory.stock_status
   FROM mes.vw_rm_store_inventory
UNION ALL
 SELECT inventory_master.inventory_id::text AS inventory_id,
    inventory_master.source_row_no,
    inventory_master.source_file,
    inventory_master.material_type,
    inventory_master.stock_stage,
    inventory_master.plant_code,
    inventory_master.storage_location,
    inventory_master.material_code,
    inventory_master.batch_no,
    inventory_master.batch_qty_mt,
    inventory_master.qa_grade,
    inventory_master.thickness_mm,
    inventory_master.width_mm,
    inventory_master.length_value,
    inventory_master.temper,
    inventory_master.coating,
    inventory_master.jet_printing,
    inventory_master.stock_generated_date,
    inventory_master.stock_age_days,
    inventory_master.mes_po,
    inventory_master.so_no,
    inventory_master.so_line_item,
    inventory_master.so_thickness_mm,
    inventory_master.so_width_mm,
    inventory_master.so_temper,
    inventory_master.so_quality,
    inventory_master.so_coating,
    inventory_master.so_min_wt_mt,
    inventory_master.so_max_wt_mt,
    inventory_master.so_logo,
    inventory_master.so_spangle,
    inventory_master.so_jet_printing,
    inventory_master.so_tll,
    inventory_master.mother_rm_batch,
    inventory_master.supplier_batch,
    inventory_master.heat_no,
    inventory_master.mother_stock_grn_date,
    inventory_master.mother_stock_grn_age_days,
    inventory_master.rm_steel_grade,
    inventory_master.carbon,
    inventory_master.manganese,
    inventory_master.sulphur,
    inventory_master.phosphorus,
    inventory_master.silicon,
    inventory_master.aluminium,
    inventory_master.carbon_equivalent,
    inventory_master.nitrogen,
    inventory_master.copper,
    inventory_master.molybdenum,
    inventory_master.chromium,
    inventory_master.nickel,
    inventory_master.rm_supplier,
    inventory_master.imported_at,
    inventory_master.updated_at,
    NULL::character varying(30) AS stock_status
   FROM mes.inventory_master
  WHERE upper(COALESCE(inventory_master.stock_stage, ''::character varying)::text) = ANY (ARRAY['WIP'::text, 'FG'::text]);
