import {useEffect,useMemo,useState} from 'react';
import {Copy,Edit3,Plus,Power,PowerOff,RefreshCw,Search,X} from 'lucide-react';
import {api,currentUser} from '../lib/api';
import {PageHeader,Status} from '../components/UI';

const blank:any={sapMaterialCode:'',materialDescription:'',materialType:'RM',materialGroup:'',productGroup:'HR',productType:'',baseUom:'MT',materialCategory:'RAW_MATERIAL',isBatchManaged:true,isActive:true};
const cat=(t:string)=>t==='FG'?'FINISHED_GOOD':t==='WIP'?'SEMI_FINISHED':'RAW_MATERIAL';
const rowForm=(r:any)=>({
  sapMaterialCode:r.sap_material_code||'',materialDescription:r.material_description||'',materialType:r.material_type||'RM',
  materialGroup:r.material_group||'',productGroup:r.product_group||'',productType:r.product_type||'',baseUom:r.base_uom||'MT',
  materialCategory:r.material_category||cat(r.material_type||'RM'),isBatchManaged:r.is_batch_managed!==false,isActive:r.is_active!==false
});

export default function MaterialMaster(){
  const[rows,setRows]=useState<any[]>([]);const[q,setQ]=useState('');const[status,setStatus]=useState('ALL');
  const[busy,setBusy]=useState(false);const[edit,setEdit]=useState<any|null>(null);const[form,setForm]=useState<any>({...blank});const[msg,setMsg]=useState('');
  const canEdit=(currentUser()?.roles||[]).includes('ADMIN');
  const load=async()=>{setBusy(true);try{const d=await api(`/masters/materials?active=all&q=${encodeURIComponent(q)}`);setRows(d.rows||[])}catch(e:any){setMsg(e.message)}finally{setBusy(false)}};
  useEffect(()=>{void load()},[]);
  const filtered=useMemo(()=>rows.filter(r=>status==='ALL'||(status==='ACTIVE'?r.is_active:!r.is_active)),[rows,status]);
  const openAdd=()=>{setEdit({mode:'add'});setForm({...blank})};
  const openEdit=(r:any)=>{setEdit(r);setForm(rowForm(r))};
  const openCopy=(r:any)=>{setEdit({mode:'copy',copySource:r.material_id});setForm({...rowForm(r),sapMaterialCode:'',isActive:true});setMsg(`Copying ${r.sap_material_code}. Enter the new Material Code and save.`)};
  const save=async()=>{setBusy(true);try{const path=edit?.material_id?`/masters/materials/${edit.material_id}`:'/masters/materials';await api(path,{method:edit?.material_id?'PUT':'POST',body:JSON.stringify(form)});setEdit(null);setMsg(edit?.material_id?'Material updated.':'Material created.');await load()}catch(e:any){setMsg(e.message)}finally{setBusy(false)}};
  const toggle=async(r:any)=>{setBusy(true);try{if(r.is_active){const c=await api(`/masters/materials/${r.material_id}/deactivation-check`);if(!c.allowed){setMsg((c.blockers||[]).map((b:any)=>`${b.label}: ${b.count}`).join(' · ')||'Material cannot be deactivated.');return;}await api(`/masters/materials/${r.material_id}/deactivate`,{method:'POST',body:'{}'})}else await api(`/masters/materials/${r.material_id}/activate`,{method:'POST',body:'{}'});await load()}catch(e:any){setMsg(e.message)}finally{setBusy(false)}};
  const modalTitle=edit?.material_id?'Edit Material':edit?.mode==='copy'?'Copy Material':'Add Material';
  return <>
    <PageHeader title="Material Master" subtitle="Approved RM, WIP and FG material structure used by routing, planning, production and quality." actions={canEdit?<button className="primary" onClick={openAdd}><Plus size={16}/> Add Material</button>:undefined}/>
    <div className="master-toolbar master-toolbar-card"><div className="master-search"><Search size={16}/><input value={q} placeholder="Material code / description / product group" onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&void load()}/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">All status</option><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select><button className="secondary-btn" onClick={()=>void load()} disabled={busy}><RefreshCw size={15}/> Refresh</button></div>
    {msg&&<div className="inline-message">{msg}</div>}
    <section className="master-table-panel professional-master-panel"><div className="master-table-scroll"><table className="master-table"><thead><tr><th>Material</th><th>Description</th><th>Type</th><th>Product Group</th><th>Category</th><th>UOM</th><th>Batch</th><th>Status</th>{canEdit&&<th>Actions</th>}</tr></thead><tbody>{filtered.map(r=><tr key={r.material_id}><td><b>{r.sap_material_code}</b></td><td>{r.material_description}</td><td>{r.material_type||'—'}</td><td>{r.product_group||'—'}</td><td>{String(r.material_category||'').replaceAll('_',' ')}</td><td>{r.base_uom}</td><td>{r.is_batch_managed?'Yes':'No'}</td><td><Status value={r.is_active?'ACTIVE':'INACTIVE'}/></td>{canEdit&&<td><div className="master-actions"><button title="Copy as New" aria-label={`Copy ${r.sap_material_code}`} onClick={()=>openCopy(r)}><Copy size={15}/></button><button title="Edit" aria-label={`Edit ${r.sap_material_code}`} onClick={()=>openEdit(r)}><Edit3 size={15}/></button><button title={r.is_active?'Deactivate':'Activate'} aria-label={`${r.is_active?'Deactivate':'Activate'} ${r.sap_material_code}`} onClick={()=>void toggle(r)}>{r.is_active?<PowerOff size={15}/>:<Power size={15}/>}</button></div></td>}</tr>)}{!filtered.length&&<tr><td colSpan={canEdit?9:8} className="empty-table-cell">No materials found.</td></tr>}</tbody></table></div><div className="table-footer"><b>{filtered.length} materials</b><small>Use Copy to create a similar material without retyping every attribute.</small></div></section>
    {edit&&<div className="modal-scrim"><div className="modal master-modal wide-master-modal"><div className="modal-head"><div><span className="screen-title-kicker">MATERIAL MASTER</span><h2>{modalTitle}</h2>{edit?.mode==='copy'&&<small className="copy-mode-note">Copied values are prefilled. Material Code is intentionally blank because it must be unique.</small>}</div><button onClick={()=>setEdit(null)}><X/></button></div><div className="master-form-grid three-col">
      <label>Material Code<input disabled={!!edit.material_id} value={form.sapMaterialCode} onChange={e=>setForm({...form,sapMaterialCode:e.target.value.toUpperCase()})}/></label><label className="wide">Description<input value={form.materialDescription} onChange={e=>setForm({...form,materialDescription:e.target.value})}/></label><label>Type<select value={form.materialType} onChange={e=>setForm({...form,materialType:e.target.value,materialCategory:cat(e.target.value)})}><option>RM</option><option>WIP</option><option>FG</option></select></label><label>Product Group<input value={form.productGroup} onChange={e=>setForm({...form,productGroup:e.target.value.toUpperCase()})}/></label><label>Base UOM<input value={form.baseUom} onChange={e=>setForm({...form,baseUom:e.target.value.toUpperCase()})}/></label><label>Category<select value={form.materialCategory} onChange={e=>setForm({...form,materialCategory:e.target.value})}><option>RAW_MATERIAL</option><option>SEMI_FINISHED</option><option>FINISHED_GOOD</option><option>SCRAP</option><option>PACKING</option><option>OTHER</option></select></label><label className="checkbox-field"><input type="checkbox" checked={!!form.isBatchManaged} onChange={e=>setForm({...form,isBatchManaged:e.target.checked})}/><span>Batch Managed</span></label><label className="checkbox-field"><input type="checkbox" checked={!!form.isActive} onChange={e=>setForm({...form,isActive:e.target.checked})}/><span>Active</span></label>
    </div><div className="modal-actions"><button onClick={()=>setEdit(null)}>Cancel</button><button className="primary" disabled={busy} onClick={()=>void save()}>{edit?.material_id?'Save Changes':'Create Material'}</button></div></div></div>}
  </>;
}
