import {useEffect,useMemo,useState} from 'react';
import {Copy,Edit3,Plus,RefreshCw,Search,X} from 'lucide-react';
import {api,currentUser} from '../lib/api';
import {PageHeader,Status} from '../components/UI';

const blank:any={companyCode:'2000',plantCode:'2000',finishedMaterialCode:'',routeIndicator:'',processPath:'',materialTree:'',validationStatus:'REVIEW',validationNotes:'',isActive:false};
const rowForm=(r:any)=>({companyCode:r.company_code||'2000',plantCode:r.plant_code||'2000',finishedMaterialCode:r.finished_material_code||'',routeIndicator:r.route_indicator||'',processPath:r.process_path||'',materialTree:r.material_tree||'',validationStatus:r.validation_status||'REVIEW',validationNotes:r.validation_notes||'',isActive:Boolean(r.is_active)});

export default function RouteMaster(){
  const[rows,setRows]=useState<any[]>([]);const[materials,setMaterials]=useState<any[]>([]);
  const[q,setQ]=useState('');const[material,setMaterial]=useState('ALL');const[status,setStatus]=useState('ALL');const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');
  const[edit,setEdit]=useState<any|null>(null);const[form,setForm]=useState<any>({...blank});const[steps,setSteps]=useState<any[]>([]);
  const canEdit=(currentUser()?.roles||[]).includes('ADMIN');
  const load=async()=>{setBusy(true);try{const d=await api(`/masters/routes?q=${encodeURIComponent(q)}&material=${material}&status=${status}`);setRows(d.rows||[]);const m=await api('/masters/materials?active=all');setMaterials((m.rows||[]).filter((x:any)=>x.material_type==='FG'))}catch(e:any){setMsg(e.message)}finally{setBusy(false)}};
  useEffect(()=>{void load()},[material,status]);
  const loadSteps=async(r:any)=>{try{const d=await api(`/masters/routes/${r.route_id}/steps`);setSteps(d.rows||[])}catch{setSteps([])}};
  const openAdd=()=>{setSteps([]);setEdit({mode:'add'});setForm({...blank})};
  const openEdit=async(r:any)=>{setEdit(r);setForm(rowForm(r));await loadSteps(r)};
  const openCopy=async(r:any)=>{setEdit({mode:'copy',copySource:r.route_id});setForm({...rowForm(r),routeIndicator:'',validationStatus:'REVIEW',validationNotes:`Copied from route ${r.route_indicator}. Review before activation.`,isActive:false});await loadSteps(r);setMsg(`Copying ${r.finished_material_code} / ${r.route_indicator}. Enter a new Route Indicator before saving.`)};
  const save=async()=>{setBusy(true);try{const path=edit?.route_id?`/masters/routes/${edit.route_id}`:'/masters/routes';await api(path,{method:edit?.route_id?'PUT':'POST',body:JSON.stringify(form)});const wasEdit=Boolean(edit?.route_id);setEdit(null);setMsg(wasEdit?'Route updated and normalized steps rebuilt.':'Route created and normalized steps built.');await load()}catch(e:any){setMsg(e.message)}finally{setBusy(false)}};
  const activeRows=useMemo(()=>rows.filter(r=>r.is_active),[rows]);
  const finished=useMemo(()=>Array.from(new Set(rows.map(r=>r.finished_material_code))).sort(),[rows]);
  const modalTitle=edit?.route_id?'Edit Route':edit?.mode==='copy'?'Copy Route':'Add Route';
  return <>
    <PageHeader title="Route Master" subtitle="Finished material route indicator, work-center sequence and material genealogy. No route logic is hardcoded in Planning or Production." actions={canEdit?<button className="primary" onClick={openAdd}><Plus size={16}/> Add Route</button>:undefined}/>
    <div className="master-toolbar master-toolbar-card"><div className="master-search"><Search size={16}/><input value={q} placeholder="Material / route / work center" onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&void load()}/></div><select value={material} onChange={e=>setMaterial(e.target.value)}><option value="ALL">All finished materials</option>{finished.map(x=><option key={String(x)}>{String(x)}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">All status</option><option>VALID</option><option>REVIEW</option><option>REJECTED</option></select><button className="secondary-btn" onClick={()=>void load()} disabled={busy}><RefreshCw size={15}/> Refresh</button></div>
    {msg&&<div className="inline-message">{msg}</div>}
    <section className="master-table-panel professional-master-panel"><div className="master-table-scroll"><table className="master-table"><thead><tr><th>Finished Material</th><th>Route</th><th>Process Path</th><th>Material Tree</th><th>Steps</th><th>Status</th><th>Notes</th>{canEdit&&<th>Actions</th>}</tr></thead><tbody>{activeRows.map(r=><tr key={r.route_id}><td><b>{r.finished_material_code}</b></td><td><b>{r.route_indicator}</b></td><td className="route-path-cell">{r.process_path}</td><td className="route-path-cell">{r.material_tree}</td><td>{r.active_steps||0}</td><td><Status value={r.validation_status}/></td><td className="notes-cell">{r.validation_notes||'—'}</td>{canEdit&&<td><div className="master-actions"><button title="Copy as New" onClick={()=>void openCopy(r)}><Copy size={15}/></button><button title="Edit" onClick={()=>void openEdit(r)}><Edit3 size={15}/></button></div></td>}</tr>)}{!activeRows.length&&<tr><td colSpan={canEdit?8:7} className="empty-table-cell">No active routes found.</td></tr>}</tbody></table></div><div className="table-footer"><b>{activeRows.length} active routes</b><small>Copied routes start in REVIEW + INACTIVE state; edit and activate them to see them here.</small></div></section>
    {edit&&<div className="modal-scrim"><div className="modal master-modal wide-master-modal"><div className="modal-head"><div><span className="screen-title-kicker">ROUTE MASTER</span><h2>{modalTitle}</h2>{edit?.mode==='copy'&&<small className="copy-mode-note">Process path and material tree are copied. Route Indicator is blank and the new route stays inactive until reviewed.</small>}</div><button onClick={()=>setEdit(null)}><X/></button></div><div className="master-form-grid three-col">
      <label>Company<input value={form.companyCode} onChange={e=>setForm({...form,companyCode:e.target.value})}/></label><label>Plant<input value={form.plantCode} onChange={e=>setForm({...form,plantCode:e.target.value})}/></label><label>Finished Material<select value={form.finishedMaterialCode} onChange={e=>setForm({...form,finishedMaterialCode:e.target.value})}><option value="">Select…</option>{materials.map(m=><option key={m.material_id} value={m.sap_material_code}>{m.sap_material_code}</option>)}</select></label><label>Route Indicator<input value={form.routeIndicator} onChange={e=>setForm({...form,routeIndicator:e.target.value.toUpperCase()})}/></label><label className="wide">Process Path<input value={form.processPath} placeholder="HRS01-PKL01-CRM01-CGL01" onChange={e=>setForm({...form,processPath:e.target.value.toUpperCase()})}/></label><label className="wide">Material Tree<input value={form.materialTree} placeholder="INPUT-WIP-WIP-FG" onChange={e=>setForm({...form,materialTree:e.target.value.toUpperCase()})}/></label><label>Validation Status<select value={form.validationStatus} onChange={e=>setForm({...form,validationStatus:e.target.value})}><option>REVIEW</option><option>VALID</option><option>REJECTED</option></select></label><label className="checkbox-field"><input type="checkbox" checked={!!form.isActive} onChange={e=>setForm({...form,isActive:e.target.checked})}/><span>Active</span></label><label className="wide">Validation Notes<textarea rows={2} value={form.validationNotes} onChange={e=>setForm({...form,validationNotes:e.target.value})}/></label>
    </div>{!!steps.length&&<div className="route-step-preview"><b>{edit?.mode==='copy'?'Source Route Steps':'Normalized Steps'}</b><div>{steps.map(s=><span key={s.route_step_id}>{s.step_no}. {s.input_material_code} → {s.work_center_code}/{s.operation_code||'—'} → {s.output_material_code}</span>)}</div></div>}<div className="modal-actions"><button onClick={()=>setEdit(null)}>Cancel</button><button className="primary" disabled={busy} onClick={()=>void save()}>{edit?.route_id?'Save Changes':'Create Route'}</button></div></div></div>}
  </>;
}
