import {useEffect,useState} from 'react';
import {Eye,FilePlus2,GitBranch,PowerOff,RefreshCw,Search,X} from 'lucide-react';
import {useNavigate} from 'react-router-dom';
import {api} from '../lib/api';import {PageHeader,Status} from '../components/UI';
export default function TDC(){
 const nav=useNavigate();const[rows,setRows]=useState<any[]>([]);const[setup,setSetup]=useState<any>({categories:[],templates:[]});const[q,setQ]=useState('');const[status,setStatus]=useState('ALL');const[category,setCategory]=useState('ALL');const[msg,setMsg]=useState('');const[reviseRow,setReviseRow]=useState<any|null>(null);const[reviseForm,setReviseForm]=useState({revisionReason:'',templateId:''});
 const load=async()=>{try{const[d,s]=await Promise.all([api(`/tdc?q=${encodeURIComponent(q)}&status=${status}&category=${category}`),api('/tdc/setup')]);setRows(d.rows||[]);setSetup(s)}catch(e:any){setMsg(e.message)}};useEffect(()=>{void load()},[]);
 const openRevise=(r:any)=>{setReviseRow(r);setReviseForm({revisionReason:'',templateId:r.template_id||''})};
 const revise=async()=>{if(!reviseRow||!reviseForm.revisionReason.trim())return;try{const d=await api(`/tdc/${reviseRow.tdc_id}/new-version`,{method:'POST',body:JSON.stringify(reviseForm)});setReviseRow(null);nav(`/quality/tdc/create?tdcId=${reviseRow.tdc_id}&version=${d.versionNo}`)}catch(e:any){setMsg(e.message)}};
 const deactivate=async(r:any)=>{const reason=prompt(`Deactivation reason for ${r.tdc_no}:`);if(!reason)return;try{await api(`/tdc/${r.tdc_id}/deactivate`,{method:'POST',body:JSON.stringify({reason})});await load()}catch(e:any){setMsg(e.message)}};
 return <><PageHeader title="TDC Register" actions={<button className="primary" onClick={()=>nav('/quality/tdc/create')}><FilePlus2 size={15}/> Create TDC</button>}/>{msg&&<div className="inline-message">{msg}</div>}
 <div className="master-toolbar master-toolbar-card"><div className="master-search"><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="TDC no / customer / code" onKeyDown={e=>e.key==='Enter'&&void load()}/></div><select value={category} onChange={e=>setCategory(e.target.value)}><option value="ALL">All categories</option>{(setup.categories||[]).filter((x:any)=>x.is_active).map((x:any)=><option key={x.category_code} value={x.category_code}>{x.category_name}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">All status</option>{['DRAFT','PENDING_QC','PENDING_PPC','PENDING_PLANT','APPROVED','RETURNED','INACTIVE'].map(x=><option key={x}>{x}</option>)}</select><button className="secondary-btn" onClick={()=>void load()}><RefreshCw size={14}/>Refresh</button></div>
 <section className="master-table-panel"><div className="master-table-scroll"><table className="master-table tdc-register-table"><thead><tr><th>TDC No</th><th>Version</th><th>Category</th><th>Customer</th><th>Plant</th><th>TDC Date</th><th>Status</th><th>Approval Stage</th><th>Template</th><th>Active</th><th>Actions</th></tr></thead><tbody>{rows.map(r=><tr key={r.tdc_id}><td><b>{r.tdc_no}</b></td><td>{r.version_label}</td><td>{r.category_name}</td><td><b>{r.customer_name}</b><small>{r.customer_code||'—'}</small></td><td>{r.plant_code}</td><td>{String(r.tdc_date||'').slice(0,10)||'—'}</td><td><Status value={r.overall_status}/></td><td>{String(r.approval_stage||'').replaceAll('_',' ')}</td><td>{r.template_name}</td><td><Status value={r.is_active?'ACTIVE':'INACTIVE'}/></td><td><div className="master-actions"><button title="View / Edit Current Version" onClick={()=>nav(`/quality/tdc/create?tdcId=${r.tdc_id}&version=${r.current_version_no}`)}><Eye size={14}/></button>{r.is_active&&r.overall_status!=='DRAFT'&&<button title="Create New Version" onClick={()=>openRevise(r)}><GitBranch size={14}/></button>}{r.is_active&&<button title="Deactivate TDC" onClick={()=>void deactivate(r)}><PowerOff size={14}/></button>}</div></td></tr>)}{!rows.length&&<tr><td colSpan={11} className="empty-table-cell">No TDCs found.</td></tr>}</tbody></table></div><div className="table-footer"><b>{rows.length} TDCs</b><small>No delete function. Approved/submitted versions are immutable.</small></div></section>
 {reviseRow&&<div className="modal-scrim"><div className="modal master-modal"><div className="modal-head"><div><h2>New TDC Version</h2><small>{reviseRow.tdc_no} · Current {reviseRow.version_label}</small></div><button onClick={()=>setReviseRow(null)}><X/></button></div><div className="master-form-grid"><label>Revision Template<select value={reviseForm.templateId} onChange={e=>setReviseForm({...reviseForm,templateId:e.target.value})}>{(setup.templates||[]).filter((x:any)=>x.template_status==='ACTIVE'&&x.is_active&&x.category_code===reviseRow.category_code).map((x:any)=><option key={x.template_id} value={x.template_id}>{x.template_name}</option>)}</select></label><label className="wide">Revision Reason<textarea rows={4} value={reviseForm.revisionReason} onChange={e=>setReviseForm({...reviseForm,revisionReason:e.target.value})} placeholder="What changed and why?"/></label></div><div className="inline-message subtle">If the selected template contains new characteristics, they will be added to the new version. Existing matching characteristic values are carried forward by Characteristic Code.</div><div className="modal-actions"><button onClick={()=>setReviseRow(null)}>Cancel</button><button className="primary" disabled={!reviseForm.revisionReason.trim()||!reviseForm.templateId} onClick={()=>void revise()}>Create New Version</button></div></div></div>}
 </>;
}
