import {useEffect,useMemo,useState} from 'react';
import {Copy,Edit3,Plus,PowerOff,RefreshCw,Trash2,X} from 'lucide-react';
import {api,currentUser} from '../lib/api';
import {PageHeader,Status} from '../components/UI';

const sectionNames:any={GENERAL:'General Data',DIMENSION:'Dimensions',CHEMICAL:'Chemical',MECHANICAL:'Mechanical',SURFACE_COATING:'Surface & Coating',DISPATCH_PACKING:'Dispatch & Packing'};
const charGroups=['TDC_GENERAL','TDC_DIMENSION','TDC_CHEMICAL','TDC_MECHANICAL','TDC_SURFACE','TDC_DISPATCH'];
const valueModes=['EXACT','MIN','MAX','RANGE','PLUS_MINUS','AS_PER_SO','AS_PER_PO','AS_PER_STANDARD','TEXT','NA'];

export default function TDCTemplateMaster(){
  const[setup,setSetup]=useState<any>({templates:[],categories:[],series:[],groups:[],characteristics:[],numberObjects:[]});
  const[selected,setSelected]=useState<any|null>(null);const[detail,setDetail]=useState<any|null>(null);const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');
  const[modal,setModal]=useState<string>('');const[source,setSource]=useState<any|null>(null);
  const[templateForm,setTemplateForm]=useState({templateCode:'',templateName:'',categoryCode:'BGL_GL',description:''});
  const[categoryForm,setCategoryForm]=useState({categoryCode:'',categoryName:'',tdcPrefix:'',description:''});
  const[seriesForm,setSeriesForm]=useState({seriesCode:'',seriesName:'',description:''});
  const[charForm,setCharForm]=useState({characteristicCode:'',characteristicName:'',groupCode:'TDC_GENERAL',dataType:'TEXT',defaultUom:'NA',defaultValueMode:'TEXT',helpText:''});
  const[mapForm,setMapForm]=useState({characteristicCode:'',sectionCode:'GENERAL',sequenceNo:100,displayLabel:'',isRequired:false,defaultValueMode:'TEXT',defaultUom:'NA',defaultSpecification:''});
  const canMaintain=(currentUser()?.roles||[]).some((x:string)=>['ADMIN','QA'].includes(x));
  const load=async()=>{setBusy(true);try{const d=await api('/tdc/setup');setSetup(d);if(selected){const still=(d.templates||[]).find((x:any)=>x.template_id===selected.template_id);if(still)await openTemplate(still,false)}}catch(e:any){setMsg(e.message)}finally{setBusy(false)}};
  useEffect(()=>{void load()},[]);
  const openTemplate=async(r:any,clear=true)=>{if(clear)setMsg('');setSelected(r);try{setDetail(await api(`/tdc/templates/${r.template_id}`))}catch(e:any){setMsg(e.message)}};
  const close=()=>{setModal('');setSource(null)};
  const saveTemplate=async(copy=false)=>{setBusy(true);try{const path=copy?`/tdc/templates/${source.template_id}/copy`:'/tdc/templates';const d=await api(path,{method:'POST',body:JSON.stringify(templateForm)});close();setMsg(copy?'New draft template copied.':'New draft template created.');await load();const row=(await api('/tdc/setup')).templates.find((x:any)=>x.template_id===d.template.template_id);if(row)await openTemplate(row)}catch(e:any){setMsg(e.message)}finally{setBusy(false)}};
  const saveCategory=async()=>{setBusy(true);try{await api('/tdc/categories',{method:'POST',body:JSON.stringify(categoryForm)});close();setMsg('TDC category created.');await load()}catch(e:any){setMsg(e.message)}finally{setBusy(false)}};
  const saveSeries=async()=>{setBusy(true);try{await api('/tdc/series',{method:'POST',body:JSON.stringify(seriesForm)});close();setMsg('TDC series created. A Number Object will be created automatically when this series is first used with a TDC prefix.');await load()}catch(e:any){setMsg(e.message)}finally{setBusy(false)}};
  const saveCharacteristic=async()=>{setBusy(true);try{await api('/tdc/characteristics',{method:'POST',body:JSON.stringify(charForm)});close();setMsg('Reusable TDC characteristic created under the selected Group Code.');await load()}catch(e:any){setMsg(e.message)}finally{setBusy(false)}};
  const addMap=async()=>{if(!selected)return;setBusy(true);try{await api(`/tdc/templates/${selected.template_id}/characteristics`,{method:'POST',body:JSON.stringify(mapForm)});close();setMsg('Characteristic added to draft template.');await openTemplate(selected)}catch(e:any){setMsg(e.message)}finally{setBusy(false)}};
  const removeMap=async(r:any)=>{if(!selected||!confirm(`Remove ${r.display_label} from this DRAFT template?`))return;try{await api(`/tdc/templates/${selected.template_id}/characteristics/${r.template_characteristic_id}`,{method:'DELETE'});await openTemplate(selected)}catch(e:any){setMsg(e.message)}};
  const activate=async()=>{if(!selected||!confirm('Activate this template? After activation it becomes immutable; future changes require Copy as New Template.'))return;try{await api(`/tdc/templates/${selected.template_id}/activate`,{method:'POST',body:'{}'});setMsg('Template activated.');await load()}catch(e:any){setMsg(e.message)}};
  const deactivate=async()=>{if(!selected||!confirm('Deactivate this template? Existing TDC versions remain unchanged.'))return;try{await api(`/tdc/templates/${selected.template_id}/deactivate`,{method:'POST',body:'{}'});setMsg('Template deactivated.');await load()}catch(e:any){setMsg(e.message)}};
  const grouped=useMemo(()=>{const o:any={};for(const r of detail?.characteristics||[])(o[r.section_code]??=[]).push(r);return o},[detail]);
  const openNewTemplate=()=>{setSource(null);setTemplateForm({templateCode:'',templateName:'',categoryCode:setup.categories?.[0]?.category_code||'BGL_GL',description:''});setModal('template')};
  const openCopy=(r:any)=>{setSource(r);setTemplateForm({templateCode:'',templateName:'',categoryCode:r.category_code,description:r.description||''});setModal('copy')};
  const openMap=()=>{const first=setup.characteristics?.[0];setMapForm({characteristicCode:first?.characteristic_code||'',sectionCode:'GENERAL',sequenceNo:100,displayLabel:first?.characteristic_name||'',isRequired:false,defaultValueMode:first?.default_value_mode||'TEXT',defaultUom:first?.default_uom||'NA',defaultSpecification:''});setModal('map')};
  return <>
    <PageHeader title="TDC Template Master" actions={canMaintain?<div className="header-actions"><button className="secondary-btn" onClick={()=>{setCategoryForm({categoryCode:'',categoryName:'',tdcPrefix:'',description:''});setModal('category')}}><Plus size={15}/> Category</button><button className="secondary-btn" onClick={()=>{setSeriesForm({seriesCode:'',seriesName:'',description:''});setModal('series')}}><Plus size={15}/> Series</button><button className="secondary-btn" onClick={()=>{setCharForm({characteristicCode:'',characteristicName:'',groupCode:'TDC_GENERAL',dataType:'TEXT',defaultUom:'NA',defaultValueMode:'TEXT',helpText:''});setModal('characteristic')}}><Plus size={15}/> Characteristic</button><button className="primary" onClick={openNewTemplate}><Plus size={15}/> New Template</button></div>:undefined}/>
    {msg&&<div className="inline-message">{msg}</div>}
    <div className="master-toolbar master-toolbar-card"><b>Plant 2000 · Company 2000</b><span className="toolbar-note">ACTIVE templates are locked. Use <b>Copy as New Template</b> whenever a characteristic or format must change.</span><button className="secondary-btn" onClick={()=>void load()} disabled={busy}><RefreshCw size={14}/>Refresh</button></div>
    <section className="master-table-panel"><div className="master-table-scroll"><table className="master-table"><thead><tr><th>Template</th><th>Category</th><th>Prefix</th><th>Characteristics</th><th>Status</th><th>Type</th><th>Actions</th></tr></thead><tbody>{(setup.templates||[]).map((r:any)=><tr key={r.template_id} className={selected?.template_id===r.template_id?'selected-row':''}><td><button className="table-link" onClick={()=>void openTemplate(r)}><b>{r.template_name}</b><small>{r.template_code}</small></button></td><td>{r.category_name}</td><td>{r.tdc_prefix}</td><td>{r.characteristic_count}</td><td><Status value={r.template_status}/></td><td>{r.is_system_template?'SYSTEM':'USER'}</td><td><div className="master-actions"><button title="Open" onClick={()=>void openTemplate(r)}><Edit3 size={14}/></button><button title="Copy as New Template" onClick={()=>openCopy(r)}><Copy size={14}/></button></div></td></tr>)}</tbody></table></div></section>
    {detail&&<section className="tdc-template-detail"><div className="tdc-section-head"><div><b>{detail.template.template_name}</b><small>{detail.template.template_code} · {detail.template.category_name} · {detail.characteristics.length} characteristics</small></div>{canMaintain&&<div className="header-actions">{detail.template.template_status==='DRAFT'&&<><button className="secondary-btn" onClick={openMap}><Plus size={14}/> Add Characteristic</button><button className="primary" onClick={()=>void activate()}>Activate Template</button></>}{detail.template.template_status==='ACTIVE'&&<><button className="secondary-btn" onClick={()=>openCopy({...detail.template,category_code:detail.template.category_code})}><Copy size={14}/> Copy as New Template</button><button className="secondary-btn danger-text" onClick={()=>void deactivate()}><PowerOff size={14}/> Deactivate</button></>}</div>}</div>
      {Object.keys(sectionNames).map(sec=>grouped[sec]?.length?<div className="tdc-template-section" key={sec}><h4>{sectionNames[sec]}</h4><div className="responsive-table"><table><thead><tr><th>#</th><th>Characteristic</th><th>Display Label</th><th>UOM</th><th>Value Mode</th><th>Required</th>{detail.template.template_status==='DRAFT'&&canMaintain&&<th>Action</th>}</tr></thead><tbody>{grouped[sec].map((r:any)=><tr key={r.template_characteristic_id}><td>{r.sequence_no}</td><td><b>{r.characteristic_name}</b><small>{r.characteristic_code}</small></td><td>{r.display_label}</td><td>{r.default_uom||'—'}</td><td>{String(r.default_value_mode||'TEXT').replaceAll('_',' ')}</td><td>{r.is_required?'Yes':'No'}</td>{detail.template.template_status==='DRAFT'&&canMaintain&&<td><button className="icon-btn" title="Remove from draft template" onClick={()=>void removeMap(r)}><Trash2 size={14}/></button></td>}</tr>)}</tbody></table></div></div>:null)}
    </section>}
    <section className="tdc-number-object"><div className="tdc-section-head"><div><b>Reusable TDC Characteristic Library</b><small>Central Group Code characteristics available for any future DRAFT template and wizard section.</small></div></div><div className="responsive-table"><table><thead><tr><th>Group Code</th><th>Characteristic</th><th>Code</th><th>Data Type</th><th>Default UOM</th><th>Value Mode</th><th>Status</th></tr></thead><tbody>{(setup.characteristics||[]).map((r:any)=><tr key={r.characteristic_id}><td><b>{r.group_code}</b></td><td>{r.characteristic_name}</td><td>{r.characteristic_code}</td><td>{r.data_type}</td><td>{r.default_uom||'—'}</td><td>{String(r.default_value_mode||'TEXT').replaceAll('_',' ')}</td><td><Status value={r.is_active?'ACTIVE':'INACTIVE'}/></td></tr>)}</tbody></table></div></section>
    <section className="tdc-number-object"><div className="tdc-section-head"><div><b>TDC Number Objects</b><small>System-generated only. The counter is created automatically for a new Prefix + Series combination.</small></div></div><div className="responsive-table"><table><thead><tr><th>Plant</th><th>Prefix</th><th>Series</th><th>Current</th><th>Next TDC No</th><th>Status</th></tr></thead><tbody>{(setup.numberObjects||[]).map((r:any)=><tr key={r.number_object_id}><td>{r.plant_code}</td><td>{r.tdc_prefix}</td><td>{r.series_code}</td><td>{r.current_number}</td><td><b>{r.next_tdc_no}</b></td><td><Status value={r.is_active?'ACTIVE':'INACTIVE'}/></td></tr>)}</tbody></table></div></section>

    {(modal==='template'||modal==='copy')&&<div className="modal-scrim"><div className="modal master-modal"><div className="modal-head"><div><h2>{modal==='copy'?'Copy as New Template':'Create New Template'}</h2><small>{modal==='copy'?'The source remains unchanged. Enter a new template code and name.':'Create a blank DRAFT template, then add characteristics.'}</small></div><button onClick={close}><X/></button></div><div className="master-form-grid"><label>Template Code<input value={templateForm.templateCode} onChange={e=>setTemplateForm({...templateForm,templateCode:e.target.value.toUpperCase().replace(/\s/g,'_')})}/></label><label>Template Name<input value={templateForm.templateName} onChange={e=>setTemplateForm({...templateForm,templateName:e.target.value})}/></label><label>Category<select value={templateForm.categoryCode} onChange={e=>setTemplateForm({...templateForm,categoryCode:e.target.value})}>{setup.categories.filter((x:any)=>x.is_active).map((x:any)=><option key={x.category_code} value={x.category_code}>{x.category_name} ({x.tdc_prefix})</option>)}</select></label><label className="wide">Description<textarea rows={3} value={templateForm.description} onChange={e=>setTemplateForm({...templateForm,description:e.target.value})}/></label></div><div className="modal-actions"><button onClick={close}>Cancel</button><button className="primary" disabled={busy} onClick={()=>void saveTemplate(modal==='copy')}>{modal==='copy'?'Create Copied Draft':'Create Draft Template'}</button></div></div></div>}
    {modal==='category'&&<div className="modal-scrim"><div className="modal master-modal"><div className="modal-head"><h2>New TDC Category</h2><button onClick={close}><X/></button></div><div className="master-form-grid"><label>Category Code<input value={categoryForm.categoryCode} onChange={e=>setCategoryForm({...categoryForm,categoryCode:e.target.value.toUpperCase().replace(/\s/g,'_')})}/></label><label>Category Name<input value={categoryForm.categoryName} onChange={e=>setCategoryForm({...categoryForm,categoryName:e.target.value})}/></label><label>TDC Prefix<input value={categoryForm.tdcPrefix} onChange={e=>setCategoryForm({...categoryForm,tdcPrefix:e.target.value.toUpperCase().replace(/\s/g,'')})}/></label><label className="wide">Description<textarea rows={3} value={categoryForm.description} onChange={e=>setCategoryForm({...categoryForm,description:e.target.value})}/></label></div><div className="modal-actions"><button onClick={close}>Cancel</button><button className="primary" onClick={()=>void saveCategory()}>Create Category</button></div></div></div>}
    {modal==='series'&&<div className="modal-scrim"><div className="modal master-modal"><div className="modal-head"><h2>New TDC Series</h2><button onClick={close}><X/></button></div><div className="master-form-grid"><label>Series Code<input value={seriesForm.seriesCode} onChange={e=>setSeriesForm({...seriesForm,seriesCode:e.target.value.toUpperCase().replace(/\s/g,'')})}/></label><label>Series Name<input value={seriesForm.seriesName} onChange={e=>setSeriesForm({...seriesForm,seriesName:e.target.value})}/></label><label className="wide">Description<textarea rows={3} value={seriesForm.description} onChange={e=>setSeriesForm({...seriesForm,description:e.target.value})}/></label></div><div className="modal-actions"><button onClick={close}>Cancel</button><button className="primary" onClick={()=>void saveSeries()}>Create Series</button></div></div></div>}
    {modal==='characteristic'&&<div className="modal-scrim"><div className="modal master-modal wide-master-modal"><div className="modal-head"><div><h2>New Reusable Characteristic</h2><small>It will also be created as a Code Detail under the selected central Group Code.</small></div><button onClick={close}><X/></button></div><div className="master-form-grid three-col"><label>Characteristic Code<input value={charForm.characteristicCode} onChange={e=>setCharForm({...charForm,characteristicCode:e.target.value.toUpperCase().replace(/\s/g,'_')})}/></label><label>Characteristic Name<input value={charForm.characteristicName} onChange={e=>setCharForm({...charForm,characteristicName:e.target.value})}/></label><label>Group Code<select value={charForm.groupCode} onChange={e=>setCharForm({...charForm,groupCode:e.target.value})}>{charGroups.map(x=><option key={x}>{x}</option>)}</select></label><label>Data Type<select value={charForm.dataType} onChange={e=>setCharForm({...charForm,dataType:e.target.value})}><option>TEXT</option><option>NUMBER</option><option>BOOLEAN</option><option>DATE</option></select></label><label>Default UOM<input value={charForm.defaultUom} onChange={e=>setCharForm({...charForm,defaultUom:e.target.value.toUpperCase()})}/></label><label>Value Mode<select value={charForm.defaultValueMode} onChange={e=>setCharForm({...charForm,defaultValueMode:e.target.value})}>{valueModes.map(x=><option key={x}>{x}</option>)}</select></label><label className="wide">Help Text<textarea rows={3} value={charForm.helpText} onChange={e=>setCharForm({...charForm,helpText:e.target.value})}/></label></div><div className="modal-actions"><button onClick={close}>Cancel</button><button className="primary" onClick={()=>void saveCharacteristic()}>Create Characteristic</button></div></div></div>}
    {modal==='map'&&<div className="modal-scrim"><div className="modal master-modal wide-master-modal"><div className="modal-head"><h2>Add Characteristic to Draft Template</h2><button onClick={close}><X/></button></div><div className="master-form-grid three-col"><label>Characteristic<select value={mapForm.characteristicCode} onChange={e=>{const c=setup.characteristics.find((x:any)=>x.characteristic_code===e.target.value);setMapForm({...mapForm,characteristicCode:e.target.value,displayLabel:c?.characteristic_name||'',defaultValueMode:c?.default_value_mode||'TEXT',defaultUom:c?.default_uom||'NA'})}}>{setup.characteristics.filter((x:any)=>x.is_active).map((x:any)=><option key={x.characteristic_code} value={x.characteristic_code}>{x.characteristic_name} · {x.group_code}</option>)}</select></label><label>Section<select value={mapForm.sectionCode} onChange={e=>setMapForm({...mapForm,sectionCode:e.target.value})}>{Object.entries(sectionNames).map(([k,v]:any)=><option key={k} value={k}>{v}</option>)}</select></label><label>Sequence<input type="number" value={mapForm.sequenceNo} onChange={e=>setMapForm({...mapForm,sequenceNo:Number(e.target.value)})}/></label><label>Display Label<input value={mapForm.displayLabel} onChange={e=>setMapForm({...mapForm,displayLabel:e.target.value})}/></label><label>UOM<input value={mapForm.defaultUom} onChange={e=>setMapForm({...mapForm,defaultUom:e.target.value.toUpperCase()})}/></label><label>Value Mode<select value={mapForm.defaultValueMode} onChange={e=>setMapForm({...mapForm,defaultValueMode:e.target.value})}>{valueModes.map(x=><option key={x}>{x}</option>)}</select></label><label className="checkbox-field"><input type="checkbox" checked={mapForm.isRequired} onChange={e=>setMapForm({...mapForm,isRequired:e.target.checked})}/><span>Mandatory in TDC</span></label><label className="wide">Default Specification (optional)<textarea rows={2} value={mapForm.defaultSpecification} onChange={e=>setMapForm({...mapForm,defaultSpecification:e.target.value})}/></label></div><div className="modal-actions"><button onClick={close}>Cancel</button><button className="primary" onClick={()=>void addMap()}>Add to Template</button></div></div></div>}
  </>;
}
