import {useEffect,useMemo,useState} from 'react';
import {Copy,Edit3,Plus,RefreshCw,Search,X} from 'lucide-react';
import {api,currentUser} from '../lib/api';
import {PageHeader,Status} from '../components/UI';

const blank:any={materialCode:'',productGroup:'GL',coatingGsm:'',variantNo:1,finishedTarget:'',finishedTolerance:'0.005',crTarget:'',crTolerance:'0.005',hrTarget:'',hrMin:'',hrMax:'',validationStatus:'REVIEW',validationNotes:'',isActive:false,effectiveFrom:'',effectiveTo:''};
const val=(v:any)=>v===null||v===undefined?'':String(v);
const fmt3=(v:any)=>v===null||v===undefined?'—':Number(v).toFixed(3);
const calc=(target:any,tol:any,dir:-1|1)=>target===''||target===null||target===undefined?'—':(Number(target)+dir*Number(tol||0.005)).toFixed(3);
const rowForm=(r:any)=>({materialCode:val(r.material_code),productGroup:val(r.product_group),coatingGsm:val(r.coating_gsm),variantNo:r.matrix_variant_no||1,finishedTarget:val(r.finished_thk_target_mm),finishedTolerance:val(r.finished_tolerance_mm||0.005),crTarget:val(r.cr_thk_target_mm),crTolerance:val(r.cr_tolerance_mm||0.005),hrTarget:val(r.hr_thk_target_mm),hrMin:val(r.hr_thk_min_mm),hrMax:val(r.hr_thk_max_mm),validationStatus:r.validation_status||'REVIEW',validationNotes:r.validation_notes||'',isActive:Boolean(r.is_active),effectiveFrom:r.effective_from?String(r.effective_from).slice(0,10):'',effectiveTo:r.effective_to?String(r.effective_to).slice(0,10):''});

export default function ThicknessMatrix(){
  const[rows,setRows]=useState<any[]>([]);
  const[q,setQ]=useState('');const[status,setStatus]=useState('ALL');const[pg,setPg]=useState('ALL');
  const[busy,setBusy]=useState(false);const[edit,setEdit]=useState<any|null>(null);const[form,setForm]=useState<any>({...blank});const[message,setMessage]=useState('');
  const canEdit=(currentUser()?.roles||[]).includes('ADMIN');
  const productGroups=useMemo(()=>Array.from(new Set(rows.map(r=>r.product_group).filter(Boolean))).sort(),[rows]);
  const load=async()=>{setBusy(true);try{const d=await api(`/masters/thickness-matrix?q=${encodeURIComponent(q)}&status=${status}&productGroup=${pg}`);setRows(d.rows||[])}catch(e:any){setMessage(e.message)}finally{setBusy(false)}};
  useEffect(()=>{void load()},[status,pg]);
  const openAdd=()=>{setEdit({mode:'add'});setForm({...blank})};
  const openEdit=(r:any)=>{setEdit(r);setForm(rowForm(r))};
  const nextVariant=(r:any,sourceRows:any[]=rows)=>Math.max(0,...sourceRows.filter(x=>String(x.material_code||'')===String(r.material_code||'')&&Number(x.coating_gsm||0)===Number(r.coating_gsm||0)&&Number(x.finished_thk_target_mm||0)===Number(r.finished_thk_target_mm||0)).map(x=>Number(x.matrix_variant_no||1)))+1;
  const openCopy=async(r:any)=>{let sourceRows=rows;try{const d=await api('/masters/thickness-matrix?q=&status=ALL&productGroup=ALL');sourceRows=d.rows||rows}catch{}const variantNo=nextVariant(r,sourceRows);setEdit({mode:'copy',copySource:r.matrix_id});setForm({...rowForm(r),variantNo,validationStatus:'REVIEW',validationNotes:`Copied from ${r.source_uuid||'existing row'}. Review before activation.`,isActive:false});setMessage(`Thickness row copied as Variant ${variantNo}. Review values before activation.`)};
  const save=async()=>{try{setBusy(true);const path=edit?.matrix_id?`/masters/thickness-matrix/${edit.matrix_id}`:'/masters/thickness-matrix';await api(path,{method:edit?.matrix_id?'PUT':'POST',body:JSON.stringify(form)});const wasEdit=Boolean(edit?.matrix_id);setEdit(null);setMessage(wasEdit?'Thickness matrix updated.':'Thickness matrix created. Min/Max derived from tolerance master.');await load()}catch(e:any){setMessage(e.message)}finally{setBusy(false)}};
  const modalTitle=edit?.matrix_id?'Edit Thickness Matrix':edit?.mode==='copy'?'Copy Thickness Matrix':'Add Thickness Matrix';
  return <>
    <PageHeader title="Thickness Matrix" subtitle="Plant 2000 · Finished/GL and CR Min-Max are derived from configurable tolerance. Approved workbook rule: ±0.005 mm." actions={<div className="master-header-actions"><span className="plant-scope-chip">Plant 2000 · CIPL</span><span className="tolerance-rule-chip">Tolerance ±0.005 mm</span>{canEdit&&<button className="primary" onClick={openAdd}><Plus size={17}/> Add Matrix Row</button>}</div>}/>
    <div className="master-toolbar master-toolbar-card"><div className="master-search"><Search size={17}/><input placeholder="Material / product group / UUID" value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&void load()}/></div><select value={pg} onChange={e=>setPg(e.target.value)}><option value="ALL">All product groups</option>{productGroups.map(x=><option key={String(x)} value={String(x)}>{String(x)}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">All status</option><option>VALID</option><option>REVIEW</option><option>REJECTED</option></select><button className="secondary-btn" onClick={()=>void load()} disabled={busy}><RefreshCw size={16}/> Refresh</button></div>
    {message&&<div className="inline-message">{message}</div>}
    <section className="master-table-panel professional-master-panel"><div className="master-table-scroll"><table className="master-table thickness-table"><thead><tr><th>UUID</th><th>Material</th><th>Variant</th><th>GSM</th><th>Finished / GL</th><th>CR</th><th>HR Input Range</th><th>Status</th><th>Active</th><th>Notes</th>{canEdit&&<th>Actions</th>}</tr></thead><tbody>{rows.map(r=><tr key={r.matrix_id} className={!r.is_active?'inactive-row':''}><td><b>{r.source_uuid}</b><small>Row {r.source_row_no??'—'}</small></td><td><b>{r.material_code}</b><small>{r.product_group}</small></td><td>{r.matrix_variant_no||1}</td><td>{fmt3(r.coating_gsm)}</td><td><b>{fmt3(r.finished_thk_target_mm)} mm</b><small>{fmt3(r.finished_thk_min_mm)} – {fmt3(r.finished_thk_max_mm)} · ±{fmt3(r.finished_tolerance_mm)}</small></td><td><b>{fmt3(r.cr_thk_target_mm)} mm</b><small>{fmt3(r.cr_thk_min_mm)} – {fmt3(r.cr_thk_max_mm)} · ±{fmt3(r.cr_tolerance_mm)}</small></td><td><b>{fmt3(r.hr_thk_target_mm)} mm</b><small>{fmt3(r.hr_thk_min_mm)} – {fmt3(r.hr_thk_max_mm)}</small></td><td><Status value={r.validation_status}/></td><td><Status value={r.is_active?'ACTIVE':'INACTIVE'}/></td><td className="notes-cell">{r.validation_notes||'—'}</td>{canEdit&&<td><div className="master-actions"><button title="Copy as New Variant" onClick={()=>void openCopy(r)}><Copy size={15}/></button><button title="Edit" onClick={()=>openEdit(r)}><Edit3 size={15}/></button></div></td>}</tr>)}{!rows.length&&<tr><td colSpan={canEdit?11:10} className="empty-table-cell">No matrix rows found.</td></tr>}</tbody></table></div><div className="table-footer"><b>{rows.length} rows</b><small>Copy automatically proposes the next Variant and keeps it REVIEW + INACTIVE until approved.</small></div></section>
    {edit&&<div className="modal-scrim master-editor-scrim"><div className="modal master-modal wide-master-modal"><div className="modal-head"><div><span className="screen-title-kicker">PLANT 2000 MASTER</span><h2>{modalTitle}</h2>{edit?.mode==='copy'&&<small className="copy-mode-note">The source values are copied into a new variant. The new row is not active until you review and approve it.</small>}</div><button onClick={()=>setEdit(null)}><X/></button></div><div className="tolerance-guard">Min/Max are system-derived from Target ± Tolerance. This prevents accidental 0.050 mm entry. Current approved tolerance is <b>0.005 mm</b>.</div><div className="master-form-grid three-col">
      <label>Material<input value={form.materialCode} onChange={e=>setForm({...form,materialCode:e.target.value.toUpperCase()})}/></label><label>Product Group<select value={form.productGroup} onChange={e=>setForm({...form,productGroup:e.target.value})}><option>GL</option><option>BGL</option><option>CR</option><option>HR</option></select></label><label>Coating GSM<input type="number" step="0.001" value={form.coatingGsm} onChange={e=>setForm({...form,coatingGsm:e.target.value})}/></label><label>Variant No<input type="number" min="1" step="1" value={form.variantNo} onChange={e=>setForm({...form,variantNo:e.target.value})}/></label>
      <div className="matrix-form-group"><b>Finished / GL Thickness</b><div><label>Target<input type="number" step="0.001" value={form.finishedTarget} onChange={e=>setForm({...form,finishedTarget:e.target.value})}/></label><label>Tolerance ±<input type="number" step="0.001" value={form.finishedTolerance} onChange={e=>setForm({...form,finishedTolerance:e.target.value})}/></label><label>Derived Min<input disabled value={calc(form.finishedTarget,form.finishedTolerance,-1)}/></label><label>Derived Max<input disabled value={calc(form.finishedTarget,form.finishedTolerance,1)}/></label></div></div>
      <div className="matrix-form-group"><b>CR Thickness</b><div><label>Target<input type="number" step="0.001" value={form.crTarget} onChange={e=>setForm({...form,crTarget:e.target.value})}/></label><label>Tolerance ±<input type="number" step="0.001" value={form.crTolerance} onChange={e=>setForm({...form,crTolerance:e.target.value})}/></label><label>Derived Min<input disabled value={calc(form.crTarget,form.crTolerance,-1)}/></label><label>Derived Max<input disabled value={calc(form.crTarget,form.crTolerance,1)}/></label></div></div>
      <div className="matrix-form-group"><b>HR Input Range</b><div><label>Target<input type="number" step="0.001" value={form.hrTarget} onChange={e=>setForm({...form,hrTarget:e.target.value})}/></label><label>Min<input type="number" step="0.001" value={form.hrMin} onChange={e=>setForm({...form,hrMin:e.target.value})}/></label><label>Max<input type="number" step="0.001" value={form.hrMax} onChange={e=>setForm({...form,hrMax:e.target.value})}/></label></div></div>
      <label>Validation Status<select value={form.validationStatus} onChange={e=>setForm({...form,validationStatus:e.target.value})}><option>REVIEW</option><option>VALID</option><option>REJECTED</option></select></label><label>Effective From<input type="date" value={form.effectiveFrom} onChange={e=>setForm({...form,effectiveFrom:e.target.value})}/></label><label>Effective To<input type="date" value={form.effectiveTo} onChange={e=>setForm({...form,effectiveTo:e.target.value})}/></label><label className="wide">Validation Notes<textarea rows={3} value={form.validationNotes} onChange={e=>setForm({...form,validationNotes:e.target.value})}/></label><label className="checkbox-field"><input type="checkbox" checked={form.isActive} onChange={e=>setForm({...form,isActive:e.target.checked})}/><span>Active for planning</span></label>
    </div><div className="modal-actions"><button onClick={()=>setEdit(null)}>Cancel</button><button className="primary" onClick={()=>void save()} disabled={busy}>{edit?.matrix_id?'Save Changes':'Create Matrix Row'}</button></div></div></div>}
  </>;
}
